### PR TITLE
Nerual -> Neural

### PR DESCRIPTION
**Pull request by tmielika**
**What this PR does / why we need it**: This PR fixes a typo in a README.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/1000)

### CODE REVIEW

**Comment by johnugeorge** [comment]
@tmielika can you sign CLA ?

**Comment by tmielika** [comment]
@googlebot I signed it!

**Comment by johnugeorge** [comment]
Can you rebase

**Comment by tmielika** [comment]
@johnugeorge rebased

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Pull request merged**
