### PR TITLE
Migrate to Go modules

### PR DESCRIPTION
**Pull request by andreyvelich**
We should migrate to Go modules from `dep` since it is not longer supported from 2020: https://github.com/golang/dep#dep.
Also to avoid errors like this: https://github.com/kubeflow/katib/pull/1436#issuecomment-780755216.
Currently, I am using the same package versions with `k8s.io/kubernetes v1.13.3` and `sigs.k8s.io/controller-runtime v0.1.9` which is very old.

Unfortunately, I can't switch to the newer version because of this: https://github.com/kubeflow/katib/issues/1405. 
Controller runtime doesn't have dynamic webhook creation from v0.2.0.
We should disable dynamic webhook creation, update the versions and clean-up modules.

As well I fixed folder name in `Build Docker images` GitHub actions workflow. What do you think @DomFleischmann @RFMVasconcelos  ?

Please take a look @gaocegege @johnugeorge.

### CODE REVIEW

**Comment by andreyvelich** [comment]
The tests are passed.
Can you check it @gaocegege @johnugeorge, please ?

**Comment by gaocegege** [comment]
Should we use K8s v1.16.9 like tf-operator https://github.com/kubeflow/tf-operator/blob/master/go.mod#L33

**Comment by andreyvelich** [comment]
> Should we use K8s v1.16.9 like tf-operator https://github.com/kubeflow/tf-operator/blob/master/go.mod#L33

I think once we fix problems with Webhooks we can directly switch to the latest version of controller-runtime and K8s.
E.g. v1.19 or v1.20

**Pull request merged**
