### PR TITLE
UI: Change adding a template

### PR DESCRIPTION
**Pull request by andreyvelich**
Related: https://github.com/kubeflow/katib/issues/641.

I fixed issue 1 and 2 from the list. 
1) I added label to the template name.
2) User can't accept template without name or yaml structure.

/cc @richardsliu @johnugeorge

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/656)

### CODE REVIEW

**Comment by johnugeorge** [comment]
@andreyvelich can you rebase?

**Comment by andreyvelich** [comment]
@johnugeorge Done

**Comment by andreyvelich** [comment]
@richardsliu I fixed conflicts, lgtm again it, please

**Pull request merged**
