### PR TITLE
fix(ui): update None Collector with Push Collector.

### PR DESCRIPTION
**Pull request by Electronic-Waste**
**What this PR does / why we need it**:

After we rename `None` collector to `Push` collector in https://github.com/kubeflow/katib/pull/2369, we have not updated the UI so far. So I do some changes in the UI package.

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by Electronic-Waste** [comment]
PTAL👀 @kubeflow/wg-automl-leads if you have time.

**Review by tenzen-y — COMMENTED** [review]
/lgtm
/approve
/hold until https://github.com/kubeflow/katib/pull/2384

**Comment by Electronic-Waste** [comment]
I'm sorry that I missed updating some `None` fields in the code. Now I have replaced all of them.

**Comment by andreyvelich** [comment]
@Electronic-Waste Please rebase this PR, so e2e should be fixed.

**Review by tenzen-y — COMMENTED** [review]
Awesome!
/lgtm
/approve

/hold cancel

**Pull request merged**
