### PR TITLE
WIP: Build image for POWER platform

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:

As we discussed in https://github.com/kubeflow/kubeflow/issues/4133, to let kubeflow supports POWER platform, we need to build docker image for ppc64le. 

The PR is going to try build the dicker image using cross build and multi-arch to build images for x86_64 and ppc64le.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/776)

### CODE REVIEW

**Comment by gaocegege** [comment]
Thanks for your contribution. But I think it does not work if other images do not change

**Comment by jinchihe** [comment]
> Thanks for your contribution. But I think it does not work if other images do not change

Thanks @gaocegege , Yes, totally agree with you. As I mark to "WIP" to avoid merging, we have no experience for this, just update one and try (investigateing) the solution can be work... if that works fine, I will update others. :-)

**Comment by gaocegege** [comment]
Gotcha, thanks. LGTM

**Comment by jinchihe** [comment]
Seems this way works, the multi-arch docker images can be built by cross building.

@hougangliu Could you please help to list which docker images are need to be updated in katib, I will update all needed images. Thanks.

/cc @gyliu513

**Comment by hougangliu** [comment]
Hi @jinchihe thanks for your PR, please refer katib image list to https://github.com/kubeflow/katib/blob/master/scripts/v1alpha3/build.sh

**Comment by jinchihe** [comment]
After discussion, we need to suspend this since take too long time to build POWER image using cross build if have `pip install ...`. Close the ticket temporary.

**Pull request closed without merging**
