### PR TITLE
feat: Add limit for suggestion pod

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

**What this PR does / why we need it**:

Now the resource limitation is hard-coded. In the future, it should be configured in katib-config.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/932)

### CODE REVIEW

**Comment by johnugeorge** [comment]
@gaocegege 
can you do a dummy push again?   CI is acting wierd without tide plugin getting effect.

**Comment by gaocegege** [comment]
@johnugeorge Should I do it now? It seems that CI passed.

**Pull request merged**
