### PR TITLE
feat: Show experiment status in json

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

**What this PR does / why we need it**:

Not sure if we want it. Richard complains that we do not show experiment info in UI, and I am not good at data-visualization. Thus use react-json-view to visualize json directly.

图片

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/853)

### CODE REVIEW

**Comment by gaocegege** [comment]
@johnugeorge Does it work for you?

**Comment by johnugeorge** [comment]
This needs a rebase?

**Comment by gaocegege** [comment]
Rebased, need LGTM

**Pull request merged**
