### PR TITLE
[WIP] Decoupling DB interface from vizier manager

### PR DESCRIPTION
**Pull request by achalshant**
Goal: To decouple the DB interface from the vizier manager. Please refer to the proposal doc for more details - https://docs.google.com/document/d/1xAi4V9SCAVZvrwiVc6a3VpK7BXPx-liQbr6YPdqBThs/edit#heading=h.1hri22e2jta

Major changes: 
1. pkg/db/interface.go was moved to run as a service in cmd/dbif/mysql/main.go
2. cmd/manager/main.go is now a thin client that connects to the DBIF service using GRPC and operates on the DB.
3. Some services and messages from api.proto have moved to dbif.proto.

Questions:
1. Are the naming conventions for the new service okay?
2. Have the new files been placed in the appropriate packages?
3. How would I package the new service and link it with ksonnet? Right now it's described in manifests/vizier/dbif/mysql.

@richardsliu @YujiOshima @johnugeorge

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/431)

### CODE REVIEW

**Comment by richardsliu** [comment]
@achalshant Thank you for doing this work.

I have a general concern - this PR is making quite a lot of changes in the current controller implementation. Perhaps it would be better to create subdirectories under cmd and pkg for v1alpha2. Then the Docker image can point to the entrypoint accordingly.

The tf-operator logic follows this pattern: https://github.com/kubeflow/tf-operator

**Comment by richardsliu** [comment]
@zhenghuiwang Please also review.

**Comment by johnugeorge** [comment]
I agree with @richardsliu .  It is better to move these changes to separate v1alpha2 version so that both versions can work independently.

**Comment by johnugeorge** [comment]
You may also wait till https://github.com/kubeflow/katib/pull/427 is merged. This tracks the major changes in the new GRPC API and database schema will be changed accordingly.  

In general,
With the proposed changes, what purpose does the thin client serve now(cmd/manager/main.go) ? 

@richardsliu  @YujiOshima

**Comment by achalshant** [comment]
@johnugeorge The manager will continue to orchestrate the katib services just like earlier. Instead of directly making queries to the db, it now calls a pluggable service to do that.

**Pull request closed without merging**
