### PR TITLE
update dockerfile for power build

### PR DESCRIPTION
**Pull request by dreamryx**
Update dockerfile to support build images for power.   Part of job from [kubeflow/issue/2226](https://github.com/kubeflow/kubeflow/issues/2226).

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/430)

### CODE REVIEW

**Comment by dreamryx** [comment]
I signed it!

**Comment by dreamryx** [comment]
I signed it!

**Comment by andreyvelich** [comment]
@dreamryx Are you planing to change Dockerfile for Reinforcement Learning suggestion as well? 
https://github.com/kubeflow/katib/blob/master/cmd/suggestion/nasrl/Dockerfile

**Comment by dreamryx** [comment]
@andreyvelich Thanks for your review!  I will change  the Dockerfile for Reinforcement Learning suggestion later after testing.

**Comment by dreamryx** [comment]
I signed it!

**Comment by dreamryx** [comment]
I signed it!

**Comment by dreamryx** [comment]
I signed it!

**Comment by dreamryx** [comment]
I signed it!

**Pull request closed without merging**
