### PR TITLE
Rename katib DB manager

### LINKED ISSUE #1004: rename katib-manager and katib-db
/kind feature

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
For now, when install katib, we have katib-manager and katib-db service/deployment, in fact, we should rename them to katib-db-manager and katib-mysql respectively to reduce confusion

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by hougangliu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1004 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/1006)

### CODE REVIEW

**Comment by johnugeorge** [comment]
Should we wait till next API release?

**Comment by hougangliu** [comment]
> Should we wait till next API release?

I think this PR only changes service name, API uninvolved.

**Comment by johnugeorge** [comment]
I meant, installation via Katib repo and manifest repo will be inconsistent. I am not sure if it is a problem

**Comment by hougangliu** [comment]
> I meant, installation via Katib repo and manifest repo will be inconsistent. I am not sure if it is a problem

I think there is no problem. in katib repo, we always use latest images; and in manifest repo, we use a certain tag (now it's `0.7` in manifest master). that is, when upgrade katib repo (latest images), manifest repo is not affected.

**Pull request merged**
