### PR TITLE
frontend: Rework the trial graph using ECharts in KWA

### PR DESCRIPTION
**Pull request by elenzio9**
In this PR:
- Rework the trial graph using the [ECharts](https://echarts.apache.org/en/index.html) library as we do for the experiments graph
- Enable actions in the trial graph and specifically:
    - [Data area zooming](https://echarts.apache.org/en/option.html#toolbox.feature.dataZoom), which supports rectangular coordinate
    - [Data zoom reset](https://echarts.apache.org/en/option.html#toolbox.feature.dataZoom), which resets the graph
    - [Data view](https://echarts.apache.org/en/option.html#toolbox.feature.dataView), which displays the data of the current graph
    - [Save image](https://echarts.apache.org/en/option.html#toolbox.feature.saveAsImage)
- Remove all `d3` references

<details>
  <summary>Click here for some screenshots of how the new graph will look like.</summary>

image
image
image

</details>

### CODE REVIEW

**Comment by andreyvelich** [comment]
That's amazing @elenzio9! I really like that user can better view the metrics on a plot.
Do we still need this assets: https://github.com/kubeflow/katib/tree/master/pkg/new-ui/v1beta1/frontend/src/assets/css ?

**Comment by elenzio9** [comment]
> Do we still need this assets: https://github.com/kubeflow/katib/tree/master/pkg/new-ui/v1beta1/frontend/src/assets/css ?

@andreyvelich You're right! I just removed it and pushed again.

**Comment by orfeas-k** [comment]
This looks amazing! Went through the code and it LGTM. I also built and tested the image on my cluster and it works as expected. Thank you @elenzio9!
/lgtm

cc @kimwnasptd

**Pull request merged**
