### PR TITLE
rename counter metrics

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

See https://github.com/kubeflow/tf-operator/pull/1055,  add _total suffix.

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/942)

### CODE REVIEW

**Comment by gaocegege** [comment]
/ok-to-test

/lgtm

It is more prometheus friendly.

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by yeya24** [comment]
@hougangliu  This test still failed in file-metricscollector. Is it better to fix https://github.com/kubeflow/katib/issues/945 first? WDYT?

**Comment by johnugeorge** [comment]
Can you rebase?

**Pull request merged**
