### PR TITLE
Upgrade Black to fix linting

### PR DESCRIPTION
**Pull request by jardon**
**What this PR does / why we need it**:
Black is broken due to a change in the click dependency and is fixed in version 22.3.0.  Here is a link to the [related issue](https://github.com/psf/black/issues/2964)

**Checklist:**

- [X] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by jardon** [comment]
I accidentally included a commit in here that I shouldnt have so the bots labelled it as XXL but really should be XXS or whatever.  Whoops

**Comment by johnugeorge** [comment]
Can you fix operator lint issues?

**Comment by johnugeorge** [comment]
@jardon Can you fix this ?

**Comment by johnugeorge** [comment]
Katib CI is broken due to this

@DomFleischmann @knkski @ca-scribner

**Comment by DomFleischmann** [comment]
@ca-scribner was going to pick up this PR, he will also fix the black issue.

**Comment by ca-scribner** [comment]
@johnugeorge yeah I'll sort this one out.  Thanks!

**Comment by ca-scribner** [comment]
@johnugeorge I think that sorts it out, but I'm not sure how to get the tests to run again.  `ok-to-test` is already on there

**Pull request merged**
