### PR TITLE
Enable to run Experiment without Goal

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/katib/issues/1060.

After this PR users should be able to run Experiment without specifying Goal.

/assign @johnugeorge 
/cc @borremosch

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/1065)

### CODE REVIEW

**Comment by johnugeorge** [comment]
Inorder to veerify in CI, shall we remove goal in one of the example yaml ? 
May be from tfjob example https://github.com/kubeflow/katib/blob/master/examples/v1alpha3/tfjob-example.yaml

**Comment by andreyvelich** [comment]
@johnugeorge Sure

**Comment by andreyvelich** [comment]
> Can we change or add a test case to test the feature?
> 
> Thanks

I added e2e test with this feature for TFJob Experiment.
Do you want to test it in the experiment_controller_test.go also?

**Comment by johnugeorge** [comment]
I see a problem in merging this now. If examples are updated, people trying katib release of 1.0 will see issues as code fix will not be included.  We have to hold this for some time till images are added to manifests

**Comment by andreyvelich** [comment]
@johnugeorge Sounds good to me.

**Comment by andreyvelich** [comment]
In order to not confuse user with new example of TFJob, I removed changes in the example.
As @johnugeorge mentioned above, if user uses Katib images from current 1.0 `manifests` release and new example without the goal, user will get the error.

We can update examples in the future versions and merge these changes now.

/cc @johnugeorge @gaocegege @hougangliu

**Pull request merged**
