### PR TITLE
UI: Fix unit tests

### PR DESCRIPTION
**Pull request by elenzio9**
This PR fixes the Katib unit tests. In order to run the unit tests, try:
- `npm i` to install the updated packages and after
- `npm run test` to run the tests

Related PRs: https://github.com/kubeflow/kubeflow/pull/6676, https://github.com/kubeflow/katib/pull/1974#pullrequestreview-1150544918

Signed-off-by: Elena Zioga <elena@arrikto.com>

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@johnugeorge @tenzen-y I see in the steps of the GH actions the following log
```
Requested labels: ubuntu-latest
Job defined at: kubeflow/katib/.github/workflows/test-go.yaml@refs/pull/1977/merge
Waiting for a runner to pick up this job...
```

Do you have any idea what this is?

I'll also assign myself for reviewing this one as well
/assign @kimwnasptd

**Comment by johnugeorge** [comment]
Github actions seems to be slow in picking up new runners. Looks like a rate limit.  This should be automatically triggered.

**Comment by johnugeorge** [comment]
There is a formatting issue which is breaking other PRs as well.

https://github.com/kubeflow/katib/actions/runs/3301273112/jobs/5449891807

     Checking formatting...

     src/app/pages/experiment-details/trials-graph-echarts/trials-graph-echarts.module.ts
     Code style issues found in the above file(s). Forgot to run Prettier?

Can you fix this? 

@elenzio9 Can you fix it in this PR or a separate PR?

**Comment by johnugeorge** [comment]
Can you do a code rebase as well?

**Comment by kimwnasptd** [comment]
I'd propose to have a separate PR just for the formatting, to unblock the rest of the PRs.

@johnugeorge we'll get to it ASAP

**Comment by kimwnasptd** [comment]
@elenzio9 now that https://github.com/kubeflow/katib/pull/1979 is merged can you also rebase this branch on top of the latest `master` and ensure the code is also formatted as expected?

**Comment by elenzio9** [comment]
> @elenzio9 now that #1979 is merged can you also rebase this branch on top of the latest `master` and ensure the code is also formatted as expected?

I can confirm that the code is formatted. I also rebased the branch.

**Comment by kimwnasptd** [comment]
@johnugeorge @tenzen-y I see a couple of unrelated tests failing. Do we have to re-run them or is there something else going on?

**Comment by johnugeorge** [comment]
@kimwnasptd Tests passed

**Comment by kimwnasptd** [comment]
I tried out the PR locally and can confirm it all tests pass with `npm run test`.

Next up we'll take a look at updating the GH Action for the frontend to automatically run these tests for each PR https://github.com/kubeflow/katib/blob/master/.github/workflows/test-node.yaml

/lgtm
/approve

**Pull request merged**
