### PR TITLE
Remove Chocolate Suggestion Service

### PR DESCRIPTION
**Pull request by tenzen-y**
Signed-off-by: Yuki Iwai <yuki.iwai.tz@gmail.com>

**What this PR does / why we need it**:
I removed all coded related Chocolate Suggestion Service.

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Part-of #2058

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by johnugeorge** [comment]
@andreyvelich Does it really matter as this is transparent to the user?

**Comment by andreyvelich** [comment]
> @andreyvelich Does it really matter as this is transparent to the user?

No, I think that is useful only for users who might use other algorithms from Chocolate (e.g. QuasiRandom).

**Comment by johnugeorge** [comment]
We can add this info in the release note.

**Comment by johnugeorge** [comment]
LGTM
/assign @andreyvelich

**Comment by andreyvelich** [comment]
/lgtm
@tenzen-y Feel free to unhold it.

**Comment by tenzen-y** [comment]
> Thanks @tenzen-y! @tenzen-y @gaocegege @johnugeorge @anencore94 Do we want to inform users that in 1.7 Grid is supported by Optuna ?

> We can add this info in the release note.

Sounds good.

**Comment by tenzen-y** [comment]
@andreyvelich @johnugeorge Thanks for your review!
/hold cancel

**Pull request merged**
