### PR TITLE
Change the default image for the new Katib UI

### PR DESCRIPTION
**Pull request by andreyvelich**
Related: https://github.com/kubeflow/katib/issues/1597.

As we discussed, for Kubeflow 1.4 in the default Katib manifests we will use the new Katib UI image.
We still need to make some changes in the website docs: https://github.com/kubeflow/katib/issues/1595 before the release.

I modified Katib README, please take a look.

/assign @kimwnasptd @gaocegege @johnugeorge 

/hold for the review.

### CODE REVIEW

**Comment by andreyvelich** [comment]
We should decide which image we are going to use for the new Katib UI.
Maybe we can re-use `docker.io/kubeflowkatib/katib-ui` and users can deploy `docker.io/kubeflowkatib/katib-ui:v0.11.1` for the previous UI.
Currently, AWS Test infra has only `docker.io/kubeflowkatib/katib-ui` image: https://github.com/kubeflow/testing/blob/master/aws/IaC/CDK/test-infra/config/static_config/ECR_Resources.py#L13.

/hold

**Comment by gaocegege** [comment]
docker.io/kubeflowkatib/katib-ui SGTM

**Comment by johnugeorge** [comment]
SGTM

**Comment by andreyvelich** [comment]
I am using `docker.io/kubeflowkatib/katib-ui` for the new UI.
@gaocegege @kimwnasptd @johnugeorge Please take a look.

/hold cancel

**Comment by andreyvelich** [comment]
Tests are passed, @kimwnasptd @gaocegege @johnugeorge if you are fine with the changes let's merge it.

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Pull request merged**
