### PR TITLE
fix: Resolve errors in e2e tests for cypress in Katib UI

### LINKED ISSUE #2381: Fix Katib UI Tests
Currently, Katib UI tests are broken.
Check this PR for more info: https://github.com/kubeflow/katib/pull/2313.

We should update the `cypress` version to fix it.

/good-first-issue
/area testing

### PR DESCRIPTION
**Pull request by tariq-hasan**
**What this PR does / why we need it**: This PR fixed the errors in e2e tests for cypress.

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #2381

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by tariq-hasan** [comment]
This PR relies on a commit in my forked repository: https://github.com/kubeflow/kubeflow/compare/master...tariq-hasan:kubeflow:fix-katib-ui-tests.

The commit needs to be merged into the kubeflow repository and the COMMIT file needs to be updated with the latest commit tag after the merge.

In addition any repercussions to `crud-web-apps` due to the addition of the package in `components/crud-web-apps/common/frontend/kubeflow-common-lib/package-lock.json` needs to be assessed.

**Comment by tariq-hasan** [comment]
There is a failed test for Katib UI: https://github.com/kubeflow/katib/actions/runs/9935880964/job/27442941694?pr=2384.

This is coming from the `npm ci` commands in https://github.com/kubeflow/katib/blob/master/cmd/ui/v1beta1/Dockerfile.

I will investigate the issue and fix it.

**Comment by andreyvelich** [comment]
Thank you so much for investigating this and for this fix @tariq-hasan!
Please can you submit PR into `kubeflow/kubeflow` to add this library ?

**Comment by tariq-hasan** [comment]
> Thank you so much for investigating this and for this fix @tariq-hasan!
> Please can you submit PR into `kubeflow/kubeflow` to add this library so we can take the appropriate commit for Katib repo?

Sounds good. I'll try to fix the failed Katib UI test so that I can identify if any other code changes are required for `kubeflow/kubeflow`. I am then creating a PR to merge the code changes in `kubeflow/kubeflow` and will then update this PR for review.

Failed Katib UI test: https://github.com/kubeflow/katib/actions/runs/9935880964/job/27442941694?pr=2384

**Comment by andreyvelich** [comment]
@tariq-hasan @tenzen-y It looks like `/rerun-all` is working only right now.
We might need to wait until this one will be merged to rerun specific workflow: https://github.com/estroz/rerun-actions/pull/3

**Comment by tariq-hasan** [comment]
Thank you for the clarification.

I did some further investigation on the Publish Katib Core Images workflow.

I found that the workflow fails within the final stage of the Dockerfile due to the results coming from `npm ci`.

If I replace `npm ci` with `npm install --no-package-lock` the workflow succeeds.

That said, `npm ci` uses the `package-lock.json` instead of `package.json` and is therefore a more stringent validation of the configuration in the `frontend` folder. In addition, `npm ci` is less resource-intensive compared to `npm install`. As such, I suppose that `npm install --package-no-lock` is not an option.

As `npm install --no-package-lock` succeeds and `npm ci` fails the issue could be due to the `package-lock.json` not working in the `node:14` base image as it was generated in a different environment on my local.

I will try to do some more investigation to determine why the build is failing and find an appropriate fix.

**Comment by andreyvelich** [comment]
Thank you for this deep investigation @tariq-hasan!

@kimwnasptd @elenzio9 @orfeas-k @kubeflow/wg-data-leads @ederign @alexcreasy
cc some UI folks on problems with Katib and Kubeflow UIs.
Please can you help us to resolve problems with `npm` and node ?

**Comment by orfeas-k** [comment]
@tariq-hasan @andreyvelich I think the answer is already highlighted in that previous commnet
>package-lock.json not working in the node:14 base image as it was generated in a different environment on my local.

If the build succeeds with `npm install --no-package-lock`, we 'd need to update `package-lock.json` file and commit from the same node and npm version with the one being used in the CI.

**Comment by andreyvelich** [comment]
What changes do we need to make for Kubeflow UI library ?

**Comment by ederign** [comment]
@andreyvelich I believe what @orfeas-k meant is that @tariq-hasan package-lock.json file in the PR needs to match the node (and npm) version of the node where the 'Publish Katib Core Images' is being executed.

@tariq-hasan could you please double check that ?

Also I'm new to the project, but is there a reason why we are using node 14 instead of node 16 like [kubeflow/kubeflow](https://github.com/kubeflow/kubeflow/tree/master/components/centraldashboard#development) is using?

**Comment by andreyvelich** [comment]
>Also, I'm new to the project, but is there a reason why we are upgrading to node 14 instead of node 16 like [kubeflow/kubeflow](https://github.com/kubeflow/kubeflow/tree/master/components/centraldashboard#development) is using?

I think, the common Kubeflow frontend component that we use doesn't use Node 16 today: https://github.com/kubeflow/kubeflow/blob/master/components/crud-web-apps/common/frontend/kubeflow-common-lib/package.json#L62

@tariq-hasan Did you check if cypress tests can be succeeded on Node 16 ? If yes, we should just update it.

**Comment by tariq-hasan** [comment]
I am upgrading `kubeflow-common-library` in `crud-webapps` as well as `katib-ui` to node 16.

That said, the following components are still using node 12:

- [jupyter](https://github.com/kubeflow/kubeflow/blob/f6563b293808c771db05023bccdd793528c53745/components/crud-web-apps/jupyter/Dockerfile#L25)
- [tensorboards](https://github.com/kubeflow/kubeflow/blob/f6563b293808c771db05023bccdd793528c53745/components/crud-web-apps/tensorboards/Dockerfile#L25)
- [volumes](https://github.com/kubeflow/kubeflow/blob/f6563b293808c771db05023bccdd793528c53745/components/crud-web-apps/volumes/Dockerfile#L25)
- [centraldashboard-angular](https://github.com/kubeflow/kubeflow/blob/f6563b293808c771db05023bccdd793528c53745/components/centraldashboard-angular/Dockerfile#L2)

I will also try to reproduce the build from a Dockerfile on my local to ensure that the `package-lock.json` is correctly generated.

**Comment by tariq-hasan** [comment]
Using `package-lock.json` from a build of the [Dockerfile](https://github.com/kubeflow/katib/blob/c660b3c0ea1bfa00147af81ca1b25dce7c0edff3/cmd/ui/v1beta1/Dockerfile) did not fix the errors.

However, upgrades of both `kubeflow-common-library` in `crud-webapps` as well as `katib-ui` to node 16 fixed the errors.

Please let me know if there are any feedback. I will then create a PR to move `kubeflow-common-library` to node 16.

**Comment by tenzen-y** [comment]
> Got it. As part of the PR, I will upgrade the following components from version 12 to version 16 to ensure compatibility with `kubeflow-common-library` and for the CI tests in `kubeflow/kubeflow` to pass successfully.
> 
> * [jupyter](https://github.com/kubeflow/kubeflow/blob/f6563b293808c771db05023bccdd793528c53745/components/crud-web-apps/jupyter/Dockerfile#L25)
> * [tensorboards](https://github.com/kubeflow/kubeflow/blob/f6563b293808c771db05023bccdd793528c53745/components/crud-web-apps/tensorboards/Dockerfile#L25)
> * [volumes](https://github.com/kubeflow/kubeflow/blob/f6563b293808c771db05023bccdd793528c53745/components/crud-web-apps/volumes/Dockerfile#L25)
> * [centraldashboard-angular](https://github.com/kubeflow/kubeflow/blob/f6563b293808c771db05023bccdd793528c53745/components/centraldashboard-angular/Dockerfile#L2)

Thank you for the great investigation!
Once you open the PR in the kubeflow/kubeflow repository, please put the link on this PR.

**Comment by andreyvelich** [comment]
@tariq-hasan Any success with submitting PR into `kubeflow/kubeflow` so we can fix the e2e tests in Katib UI ?

**Comment by tariq-hasan** [comment]
I apologize for the delay. I've updated the configuration for tensorboards. I am working through jupyter, volumes and centraldashboard-angular, and will create a PR in `kubeflow/kubeflow` shortly.

**Comment by andreyvelich** [comment]
Thank you @tariq-hasan, appreciate your time for it!

**Comment by tariq-hasan** [comment]
I have created a PR for `kubeflow/kubeflow`: https://github.com/kubeflow/kubeflow/pull/7637.

This PR upgrades the node version from 12 to 16 for `kubeflow-common-lib` and its dependent components: `jupyter`, `tensorboards`, `volumes` and `centraldashboard-angular`.

**Comment by tariq-hasan** [comment]
@andreyvelich @tenzen-y I was wondering if you have any thoughts on why the E2E Test with enas-cnn-cifar10 could be failing.

I have re-run it multiple times but to no success.

I have not seen this test fail before so this is quite odd.

**Review by andreyvelich — COMMENTED** [review]
Thanks for this great contribution to fix the Katib UI E2Es @tariq-hasan 🎉 
We can finally unblock the PRs for Katib UI.

**Pull request merged**
