### PR TITLE
Fix the FPGA examples documentation

### PR DESCRIPTION
**Pull request by eliaskoromilas**
**What this PR does**:

* Set `kube-system` as the suggested (InAccel FPGA Operator) namespace
* Replace broken link

The new link points to a MicroK8s + InAccel + Katib [tutorial](https://ubuntu.com/tutorials/accelerated-ml-experiments-on-microk8s-with-inaccel-fpga-operator-and-kubeflow-katib).

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Thanks for updating this documentation @eliaskoromilas!

/lgtm

**Comment by johnugeorge** [comment]
Related: #1842

**Comment by johnugeorge** [comment]
can you rebase?

**Comment by eliaskoromilas** [comment]
rebase

**Pull request merged**
