### PR TITLE
Promote @Electronic-Waste and @helenxie-bit as Katib reviewers

### PR DESCRIPTION
**Pull request by andreyvelich**
This PR proposes to promote new reviewers for Katib project:

- @Electronic-Waste for contributions to the Katib control plane and helping with other PRs.
- @helenxie-bit for contributions to the Katib SDK including enhancements in Training Operator to support `tune` API for LLMs.

Thank you for your great contributions and we are looking forward to continue working with all of you 🎉 

/assign @kubeflow/wg-automl-leads

### CODE REVIEW

**Comment by helenxie-bit** [comment]
Thank you for the recognition and the opportunity to be a reviewer for Katib! I’m grateful for the support from the community and excited to continue contributing, especially on the LLM enhancements and other improvements. Looking forward to working with everyone!

**Comment by Electronic-Waste** [comment]
Thanks for offering me such a precious opportunity to collaborate with you in Katib. You helped me a lot with my contributions, from drafting proposals to reviewing PRs. It's a pleasure for me to continue contributing to Katib and Training-Operator, from which I learned a lot and benefited a lot. 

Looking forward to working with all of you in the future! @kubeflow/wg-automl-leads @terrytangyuan  @helenxie-bit @tariq-hasan @shashank-iitbhu @shivas1516 @sandipanpanda

**Review by tenzen-y — COMMENTED** [review]
+1
/lgtm
/approve
/hold

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Comment by johnugeorge** [comment]
@helenxie-bit @Electronic-Waste Thanks for all your contributions.  Looking forward to work with yo

/lgtm

**Pull request merged**
