### PR TITLE
Add MPI operator horovod example

### PR DESCRIPTION
**Pull request by andreyvelich**
This example of using MPI operator with Horovod mnist example. Blocked by: https://github.com/kubeflow/katib/pull/1333.

Fixes: https://github.com/kubeflow/katib/issues/1181.

/assign @gaocegege @johnugeorge 

/cc @terrytangyuan @YuxiJin-tobeyjin @carmark

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Is this ready for review yet?

**Comment by andreyvelich** [comment]
@terrytangyuan Sure, it should work with merged controller code base.

**Review by terrytangyuan — APPROVED** [review]
/lgtm

**Review by carmark — APPROVED** [review]

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Review by andreyvelich — COMMENTED** [review]
/approve

**Pull request merged**
