### PR TITLE
Properly initialize CI cluster credential

### LINKED ISSUE #359: CI seems to be running on somewhere else than $CLUSTER_NAME
test/scripts/unit-test.sh creates a mysql pod for testing. During #352 it was found to contain some older DB schema, resulting a failed unit test.
I created #357 to investigate the issue. As I changed the kubeconfig set up script to just use "gcloud container clusters get-credentials ${CLUSTER_NAME}", I got this error

```
Error from server (NotFound): error when creating "STDIN": namespaces "kubeflow-test-infra" not found  
```

I think the mysql pod used to run on the cluster where argo ran.

### PR DESCRIPTION
**Pull request by toshiiw**
It has been using the cluster where argo ran

Hopefully fixes #359

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/360)

### CODE REVIEW

**Comment by YujiOshima** [comment]
@toshiiw Please rebase the latest master.

**Comment by richardsliu** [comment]
@toshiiw Is this similar to the issue you had? https://github.com/kubernetes/ingress-nginx/issues/1663

Can you try something like https://github.com/kubernetes/ingress-nginx/issues/1663#issuecomment-342821352?

**Comment by jlewi** [comment]
Is there a plan to run Katib in its own cluster. Since Katib includes cluster resources (e.g. StudyJob controller) we will inevitably have conflicts if multiple tests try to make changes and test those changes?

Are we using kfctl.sh to deploy Katib?

**Comment by richardsliu** [comment]
@jlewi Katib is currently not using kfctl. We are applying katib components directly to the cluster: https://github.com/kubeflow/katib/blob/master/scripts/deploy.sh

**Comment by YujiOshima** [comment]
@toshiiw Great! Thanks!
@richardsliu Could we merge this?

**Comment by richardsliu** [comment]
@toshiiw Can you sign the CLA and reply with "I signed it"?

**Comment by toshiiw** [comment]
@richardsliu I signed it a while ago. I'm not sure why cla/google bot is complaining now.

**Comment by toshiiw** [comment]
The infra isn't in a good shape, it seems.

> ERROR: (gcloud.builds.submit) [Errno 104] Connection reset by peer
> This may be due to network connectivity issues. Please check your network settings, and the status
of the service you are trying to reach.

**Pull request merged**
