### PR TITLE
Earlystopping changes trigger CI based on version

### PR DESCRIPTION
**Pull request by hougangliu**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/544)

### CODE REVIEW

**Comment by johnugeorge** [comment]
do we still need to keep include dirs in Katib prow?  I feel that it is error prone.

@richardsliu @gaocegege

**Comment by hougangliu** [comment]
Basically we will seldom change prow soon since after Katib components finished one by one. But including files in prow can reduce workload of CI in long term.
So I suggest to keep include dirs in Katib prow

**Comment by hougangliu** [comment]
#486 seems to have fix ui part, maybe this PR can fix the last part: earlystop
/hold cancel

**Pull request merged**
