### PR TITLE
Add hints to obtain Kubeflow and Minikube version

### PR DESCRIPTION
**Pull request by xuhdev**
Hope this helps new bug reporters

### CODE REVIEW

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

Please sign the CLA

**Comment by xuhdev** [comment]
Thanks @gaocegege ! Could you exempt this PR from CLA? This is a super tiny PR and signing corporate CLA has been always unsuccessful for me so far...

**Comment by gaocegege** [comment]
You can choose on yourself in https://cla.developers.google.com/clas

We have to sign it before we merge the code

**Comment by xuhdev** [comment]
@gaocegege I opened the link and it says I am covered by my IBM corporate agreements already. Could you refresh the CI to redetermine the CLA status? Thank you!

**Comment by gaocegege** [comment]
@googlebot I signed it!

**Pull request merged**
