### PR TITLE
fix py client import error

### PR DESCRIPTION
**Pull request by hougangliu**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/453)

### CODE REVIEW

**Comment by johnugeorge** [comment]
@hougangliu  Can you please explain why you need this change?

**Comment by hougangliu** [comment]
> @hougangliu Can you please explain why you need this change?

pipeline katib-laucher uses studyjob python client. and this patch fixes 2 import error:
1. multiprocessing is used but not import
2. util.JobTimeoutError is not defined.

When timeout occurs, the two issue triggers

**Comment by johnugeorge** [comment]
Ok. It was not used earlier 
/lgtm
/approve

**Pull request merged**
