### PR TITLE
Add cert manager install to the release script

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/katib/issues/1505.
We should add `katib-with-kubeflow-cert-manager` install to release script for updating the images.

/cc @yanniszark @gaocegege @johnugeorge

### CODE REVIEW

**Comment by andreyvelich** [comment]
I increased timeout for e2e Experiments to 50 minutes.
That should help us with testing.

**Review by gaocegege — COMMENTED** [review]
/lgtm
Thanks for your contribution! :tada: :+1:

**Pull request merged**
