### PR TITLE
Katib v1beta1 version

### PR DESCRIPTION
**Pull request by andreyvelich**
I added v1beta1 version to continue Katib development and adding new API changes.
See discussion: https://github.com/kubeflow/katib/issues/1186.

1. All API and Controller logics are the same as in v1alpha3 .

2. I didn't make doc changes in this PR, only for https://github.com/andreyvelich/katib/blob/v1beta1-version/docs/developer-guide.md, because I changed Makefile. For other doc we can make changes in the separate PR, since it will affect Kubeflow website.

3. For Makefile I changed corresponding scripts (deploy, undeploy, ..) to new v1beta1 version. Old scripts I renamed to `<script-name>v1alpha3` accordingly.

4. For Swagger I created API for v1alpha3 and v1beta1 versions. @sperlingxx Do we need to make v0.1 Swagger version for every Katib version (https://github.com/andreyvelich/katib/blob/v1beta1-version/hack/swagger/main.go#L65) ? If not, I can rename it to appropriate Katib version.

/assign @johnugeorge @gaocegege

### CODE REVIEW

**Comment by andreyvelich** [comment]
@johnugeorge @gaocegege I disabled e2e test for custom metrics collector in v1beta1.
In this PR: https://github.com/kubeflow/katib/pull/908, we didn't add the source code for the image: kubeflowkatib/custom-metrics-collector, so I can't modify it.

Currently, in this metrics collector we report metrics using `api.v1.alpha3.Manager`, but we need to use `api.v1.beta1.Manager` in the new version.

I added comment to e2e test and yaml file for the custom metrics collector.

**Comment by gaocegege** [comment]
/lgtm
/approve

I think we can merge it and fix problems in other PRs if there is any.

**Pull request merged**
