### PR TITLE
docs: remove katib workflow

### PR DESCRIPTION
**Pull request by gonmmarques**
**What this PR does / why we need it**:
Fixes # https://github.com/kubeflow/katib/issues/2442
Relates also to https://github.com/kubeflow/website/pull/3906

Let me know if I missed something.

**Checklist:**

- [x] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

In the spirit of Hacktoberfest, and if this PR is accepted, please consider adding the label "hacktoberfest-accepted”. Thanks.

### CODE REVIEW

**Review by Electronic-Waste — APPROVED** [review]
Can be merged after https://github.com/kubeflow/website/pull/3906

**Review by andreyvelich — COMMENTED** [review]
Thanks for updating this @gonmmarques!
/lgtm
/approve

**Pull request merged**
