### PR TITLE
feat: Add a flag to support removing GRPC probe at runtime

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

**What this PR does / why we need it**:

It is to add a flag to decide if we should enable the GRPC probe.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/1020)

### CODE REVIEW

**Comment by johnugeorge** [comment]
did you face any issues in your env?

**Comment by gaocegege** [comment]
/retest

Yeah for some reasons, we cannot install grpc probe in the image, thus we do not want to enable it.

**Pull request merged**
