### PR TITLE
UI: Add Metrics Collector Spec to Submit Experiment

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/katib/issues/1089.

I added functionality to add Metrics Collector Spec in submit Experiment by parameters page.

It has all available Metrics Collectors:
1. StdOut
2. File
3. TensorFlowEvent
4. PrometheusMetric
5. Custom
6. None

MC

/cc @johnugeorge @gaocegege @hougangliu

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/1096)

### CODE REVIEW

**Comment by johnugeorge** [comment]
@andreyvelich Great work. 
Is PrometheusMetric or Custom supported?

**Comment by andreyvelich** [comment]
@johnugeorge From the UI, yes.

**Comment by johnugeorge** [comment]
I meant, support from backend. will uses feel confused?

Looks ok to merge. we can implement it later

**Comment by andreyvelich** [comment]
@johnugeorge Custom collector I tried with this example: https://github.com/kubeflow/katib/blob/master/examples/v1alpha3/custom-metricscollector-example.yaml. For me it was working.

About Prometheus I am not sure that our backend supports it right now.

**Pull request merged**
