### PR TITLE
Run post-submit image build in kubeflow-ci project

### PR DESCRIPTION
**Pull request by andreyvelich**
We get this error in post-submit:
```
token exchange failed for project 'kubeflow-images-public'. 
Caller does not have permission 'storage.buckets.get'. 
To configure permissions, follow instructions at: https://cloud.google.com/container-registry/docs/access-control
```
We need to debug it.

I created new IAM with `roles/storage.admin` role for kubeflow-ci Service Account.

### CODE REVIEW

**Comment by andreyvelich** [comment]
Add Cloud Build Service Account and Storage Admin role for 
`kubeflow-testing@kubeflow-ci.iam.gserviceaccount.com` service account doesn't help.

@jlewi Can we use this SA from automl-ci project to push images to `kubeflow-images-public` ?

/cc @gaocegege @johnugeorge

**Comment by andreyvelich** [comment]
@jlewi If we can't give permission to push images that were built in `automl-ci` project, should we build them in `kubeflow-ci` project?

**Comment by andreyvelich** [comment]
As we discussed in community meeting, I switched build to `kubeflow-ci` project for post-submits.

Later we should disable publishing images to `kubeflow-images-public` in our CI.
We should add Katib to apps-cd: https://github.com/kubeflow/testing/tree/master/apps-cd.

/cc @gaocegege @johnugeorge @jlewi

**Comment by jlewi** [comment]
As discussed in the community meeting we use separate infra to build the images in kubeflow-images-public because we don't want unchecked in code to have access to that repo.

Our current infra for continuously building and updating our production images is described here
https://github.com/kubeflow/testing/tree/master/apps-cd

As discussed in the meeting options are

1. Run your image builds on kubeflow-releasing e.g. using infra mentioned above
1. Move your images into your own registry and build them however you want 
1. Request a temporary exception to continue building in kubeflow-ci or from the katib project  until one of the other methods can be improved.
      
Is there an issue tracking a long term solution for CI/CD for AutoML wg?

**Comment by andreyvelich** [comment]
@jlewi If you fine with this temporary approach that I have done in this PR, can you give your lgtm, please?

**Comment by jlewi** [comment]
/lgtm
/approve

Does the service account in kubeflow-ci have permission to write to kubeflow-images-public?

**Comment by andreyvelich** [comment]
> /lgtm
> /approve
> 
> Does the service account in kubeflow-ci have permission to write to kubeflow-images-public?

Yes, we were using it to public Katib images.

**Review by andreyvelich — COMMENTED** [review]
/approve

**Pull request merged**
