### PR TITLE
update deployment api version

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: yeya24 <yb532204897@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Since extensions/v1beta1 is deprecated since k8s 1.16, so migrating to apps/v1

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/937)

### CODE REVIEW

**Comment by gaocegege** [comment]
@yeya24 Thanks for your contribution.

You have created lots of PRs, I think you could request to join the org to let bot trigger CI for your PR automatically. Ref https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org

**Comment by yeya24** [comment]
> @yeya24 Thanks for your contribution.
> 
> You have created lots of PRs, I think you could request to join the org to let bot trigger CI for your PR automatically. Ref https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org

Thanks, I will try to open a PR for it.

**Comment by yeya24** [comment]
The e2e test only failed in `run-bayesian-e2e-tests`, see http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-katib-presubmit-e2e-v1alpha3-937-fbf6bb9-2528-df39?tab=workflow&nodeId=kubeflow-katib-presubmit-e2e-v1alpha3-937-fbf6bb9-2528-df39-2116955652. Is it a flaky test? I believe this is not related to this PR.

**Comment by gaocegege** [comment]
Yeah it seems that when the OS executes syscall `read`, error is returned. I think it is not caused by the code. Maybe network is broken.

/retest

**Comment by yeya24** [comment]
Another failed test because of the network in gcp? http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/kubeflow-katib-presubmit-e2e-v1alpha3-937-fbf6bb9-3488-9972?tab=workflow&nodeId=kubeflow-katib-presubmit-e2e-v1alpha3-937-fbf6bb9-3488-9972-456161096

**Comment by gaocegege** [comment]
/retest

Our test infra is not very stable

**Comment by johnugeorge** [comment]
@yeya24 Can you rebase?

**Comment by yeya24** [comment]
@johnugeorge  CI passed

**Pull request merged**
