### PR TITLE
*: Update name

### PR DESCRIPTION
**Pull request by gaocegege**
/assign @YujiOshima 

/hold

I prefer to merge it after CI passes. Thus blocked by #63 

Signed-off-by: Ce Gao <gaoce@caicloud.io>

### CODE REVIEW

**Comment by gaocegege** [comment]
I am not sure if it affects frontend :thinking:

**Comment by YujiOshima** [comment]
There is nothing you should modify in the frontend files. 👍

**Comment by YujiOshima** [comment]
LGTM. You can merge this after tests passed!

**Comment by gaocegege** [comment]
Thanks, I am merging it since it blocks the work #46

**Pull request merged**
