### PR TITLE
kwa(front): Update the use of SnackBarService

### PR DESCRIPTION
**Pull request by orfeas-k**
Following this [PR](https://github.com/kubeflow/kubeflow/pull/6918) and the changes implemented in SnackBarService of KF common library, this PR updates the use of SnackBarService in order to pass required data via a `config` object and provide `MAT_SNACK_BAR_DEFAULT_OPTIONS`.

### CODE REVIEW

**Comment by kimwnasptd** [comment]
@tasos-ale could you take a stab at this?

/cc @tasos-ale

**Review by tasos-ale — APPROVED** [review]
Thanks, @orfeas-k! @kimwnasptd you can merge it.

**Comment by kimwnasptd** [comment]
Thanks for taking a look!

/lgtm
/approve

**Pull request merged**
