### PR TITLE
Linting for K8s YAML files

### LINKED ISSUE #1859: Add linter for Kubernetes manifests
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

As discussed in [this](https://github.com/kubeflow/katib/issues/1734#issuecomment-972703530), it would be better to verify the format of all Kubernetes manifests in this repo by [`yamllint`](https://github.com/stackrox/kube-linter).

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

### PR DESCRIPTION
**Pull request by Rishit-dagli**
**What this PR does / why we need it**:

This PR verifies the format of YAML files in this repo using yamllint as discussed in https://github.com/kubeflow/katib/issues/1734#issuecomment-972703530 and #1859

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #1859

**Checklist:**

- [x] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by Rishit-dagli** [comment]
> Thanks @Rishit-dagli for the PR
> 
> Charmed-Katib is not maintained by community. You can create a new one.

Ah, thanks for the info. I'll create a new workflow.

**Comment by tenzen-y** [comment]
@Rishit-dagli Thanks for creating this PR!

@johnugeorge 
Should we add scripts to run on the local machines in another PR?

**Comment by johnugeorge** [comment]
we can do the same as https://github.com/kubeflow/katib/blob/master/.github/workflows/test-shell-script.yaml#L17 using `make`

Also, should we treat warnings as errors using strict flag?

**Comment by tenzen-y** [comment]
> we can do the same as https://github.com/kubeflow/katib/blob/master/.github/workflows/test-shell-script.yaml#L17 using make

SGTM @johnugeorge 
Can you update this PR like `shellcheck`? @Rishit-dagli 

> Also, should we treat warnings as errors using strict flag?

@Rishit-dagli Do we already have any manifests to hit `line-length` violations?

**Comment by anencore94** [comment]
> Also, should we treat warnings as errors using strict flag?

I agree with you @tenzen-y :) Lots of our example manifests might violates line-length rule because of useful comments for users

**Comment by johnugeorge** [comment]
https://github.com/kubeflow/katib/runs/6989547788?check_suite_focus=true

I see two warnings here 
 `  warning  missing document start "---"  (document-start)`
 `  warning  too few spaces before comment  (comments)`

**Comment by Rishit-dagli** [comment]
@tenzen-y 
> Do we already have any manifests to hit line-length violations?

Yes, please see this output for a list of the files that violate line-length: [out.txt](https://github.com/kubeflow/katib/files/8954912/out.txt)

**Comment by Rishit-dagli** [comment]
> https://github.com/kubeflow/katib/runs/6989547788?check_suite_focus=true
> 
> I see two warnings here ` warning missing document start "---" (document-start)` ` warning too few spaces before comment (comments)`

I will edit the YAML files accordingly, I believe this should be done in a separate PR since it isn't actually "adding a linter", what do you think?

**Comment by johnugeorge** [comment]
Please rebase

**Comment by Rishit-dagli** [comment]
> Please rebase

Done ✅

**Comment by Rishit-dagli** [comment]
> This pull-request has been approved by: https://github.com/kubeflow/katib/pull/1901#, https://github.com/kubeflow/katib/pull/1901#pullrequestreview-1015371680
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign johnugeorge after the PR has been reviewed.

/assign @johnugeorge

**Comment by johnugeorge** [comment]
Thanks @Rishit-dagli 

/approve

**Pull request merged**
