### PR TITLE
Remove unused katib-manager-rest

### PR DESCRIPTION
**Pull request by hougangliu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/876)

### CODE REVIEW

**Comment by johnugeorge** [comment]
I think, this will be useful to use rest calls for our DB interface.   Mostly for debugging I guess, WHYT?

**Comment by hougangliu** [comment]
for now, only metrics related operations (create/delete/get) are available. I think the rest service is of little value now.

**Comment by gaocegege** [comment]
SGTM

/lgtm

**Comment by hougangliu** [comment]
@johnugeorge 
katib-manager-rest is introduced in v1alpha1 when katib-manager works as a core role by which controller persists studyjob info into db and call it to get suggestion result, 3rd-party can call it to check StudyJob information (katib UI), suggestion service to call it to check trial result or else. by katib-manager-rest, 3rd-party can get studyjob info in REST way.
now, katib-manager just plays an internal DB interface role to persist only metrics and 3rd-party doesn't need it. so katib-manager-rest can say goodbye now.
WDYT?

**Comment by johnugeorge** [comment]
Sounds good.  Just thinking if it is late to add to 0.7 release?

**Comment by hougangliu** [comment]
> Sounds good. Just thinking if it is late to add to 0.7 release?

The risk is little since the change doesn't change katib-manger, katib-controller and suggestion algorithm code.

**Pull request merged**
