### PR TITLE
fix: Ignore the failure

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

**What this PR does / why we need it**:

When katib-controller is unavailable, the mutation webhook will fail all the pods in the namespace. I think we should avoid it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/996)

### CODE REVIEW

**Comment by johnugeorge** [comment]
When did you encounter this issue?

**Comment by gaocegege** [comment]
For example, there is a namespace which enables the injections. When I created a TFJob and the katib-controller is not ready at that time, the TFJob will be rejected since the webhook fails.

**Pull request merged**
