### PR TITLE
Add manifests/dlk in deploy.sh

### PR DESCRIPTION
**Pull request by vinaykakade**
While working through the getting started instructions, noticed that manifests/dlk is not part of deploy.sh, and so the examples do not work and the workers are not spawned. Verified that the workers are spawned correctly after adding manifests/dlk to deploy.sh

cc @mayankjuneja

### CODE REVIEW

**Comment by vinaykakade** [comment]
@YujiOshima - are you able to take a quick look at this change?

**Comment by YujiOshima** [comment]
@vinaykakade The dlk is already deprecated after #74.
We don't need dlk deployment in the latest code.
We will release a new version soon. Please use it.
@gaocegege Could you release v0.1.2-alpha with the current master?

**Comment by gaocegege** [comment]
@YujiOshima Done

@vinaykakade Thanks for your contribution while I think maybe we do not need to add dlk anymore, could you please close the issue?

**Comment by gaocegege** [comment]
And, if you are interested in the development of katib, you could get start with these issues: https://github.com/kubeflow/katib/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

 :smile:

**Comment by vinaykakade** [comment]
Thanks, closing this. BTW, since dlk is no longer used, the references to it should be deleted from the top level manifests, but that is a topic of separate issue!

**Comment by gaocegege** [comment]
@YujiOshima 

Should we remove dlk from the repository? Maybe we could open an issue.

**Comment by YujiOshima** [comment]
@gaocegege @vinaykakade 
Yes, we should remove. I'm sorry to forget to remove it.
@vinaykakade Thank you!!

**Pull request closed without merging**
