### PR TITLE
UI: Add delete experiment functionality

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/katib/issues/640

/cc @richardsliu @johnugeorge

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/654)

### CODE REVIEW

**Comment by andreyvelich** [comment]
I fixed the conflicts. Please lgtm this again @richardsliu @johnugeorge

**Comment by johnugeorge** [comment]
\lgtm

**Pull request merged**
