### PR TITLE
Use release tags for Trial images 

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/katib/issues/1554.
I added latest tag for Trial images.
For SDK examples, I use release tags, since we are installing specific version of Katib SDK.

Also, I modified `update-images` script to re-use it in release and e2e tests.
Currently, this script updates all Katib images that we maintain.

Please take a look.

/assign @gaocegege @tenzen-y @anencore94 @johnugeorge

### CODE REVIEW

**Comment by tenzen-y** [comment]
LGTM 👍
/lgtm
/hold

**Review by tenzen-y — COMMENTED** [review]
LGTM 👍
/lgtm
/hold

**Comment by andreyvelich** [comment]
This PR should be ready.
/hold for the review

**Review by anencore94 — APPROVED** [review]
LGTM!
just a small question: Is there some special reason to use semantic version in notebook files rather than using `latest` ?

**Comment by andreyvelich** [comment]
> Is there some special reason to use semantic version in notebook files rather than using `latest`

Since we install the specific version of Katib SDK in our notebooks, it's better to be consistent with the Trial images.

**Comment by andreyvelich** [comment]
@ca-scribner @DomFleischmann Any ideas why Charms can fail ?

**Pull request merged**
