### PR TITLE
kwa(front): Add UI tests with Cypress 

### PR DESCRIPTION
**Pull request by orfeas-k**
This PR adds UI tests with Cypress for functionalities of the KWA frontend. More specifically, they check that:

 - New Experiment form page loads template without errors.
 - Index page
    * has an "Experiments" title
    * lists experiments without errors
    * renders every experiment name into the table
    * renders properly Status icon for all experiments

Everything implementation-specific (mock API, node version etc) mentioned in the [VWA UI tests PR](https://github.com/kubeflow/kubeflow/pull/6862) stand for this one too.

### CODE REVIEW

**Comment by orfeas-k** [comment]
@elenzio9 Good observation! I fixed this and pushed again.

**Comment by elenzio9** [comment]
Other than that it looks great! Thank you @orfeas-k!
cc @kimwnasptd
/lgtm

**Comment by orfeas-k** [comment]
The failed job `Go Test / Unit Test` is flaky as @tenzen-y mentioned here https://github.com/kubeflow/katib/pull/1979#issuecomment-1288911322. 

@kubeflow/wg-automl-leads Can you restart the failed GH-Actions Job?

**Comment by kimwnasptd** [comment]
Looks good, thanks for the work @orfeas-k and the review @elenzio9!

/lgtm
/approve

**Review by tenzen-y — COMMENTED** [review]
/approve

**Pull request merged**
