### PR TITLE
Set TrialName from the GetSuggestionReply

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/katib/issues/610.

After this PR, we can set Name of the Trial from the Suggestion.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/624)

### CODE REVIEW

**Comment by johnugeorge** [comment]
In longer run, we need to move to a design where Trial is created in controller itself while suggestions give just parameter assignments.  Is there a better way to handle this?

**Comment by andreyvelich** [comment]
@johnugeorge What if Suggestion wants to know which trial was created on the previous run? 
How we can handle, if Suggestion sends only  parameter assignments?
/cc @gaocegege @hougangliu @richardsliu

**Comment by johnugeorge** [comment]
can we get it from the trial list?

**Comment by andreyvelich** [comment]
@johnugeorge If we use TrialList, how Suggestion understands on what steps what trial was created ? 
TrialList returns all Trial names.

**Comment by johnugeorge** [comment]
Holding this PR till we decide the design
/hold

**Pull request closed without merging**
