### PR TITLE
Refine API

### PR DESCRIPTION
**Pull request by YujiOshima**
Related #72 #66 #68 
* Add low-level API and refine APIs
* Split Trial to Worker(an instance of evaluating processes) and Trial (a parameter set).
* Migrate dkl worker to kubernetes worker.
* Save suggestion and Early stopping configs to DB
* Add MinikubeDemo

HyperBand and Bayes optimization suggestion are not supported in this PR.
Random and Grid Support for now.

@gaocegege 
@ddysher 

Signed-off-by: YujiOshima <yuji.oshima0x3fd@gmail.com>

### CODE REVIEW

**Comment by gaocegege** [comment]
🎉 Thanks for your contribution

It is a little monolithic, I will reivew it ASAP

**Comment by gaocegege** [comment]
Generally LGTM, I will have a try on it.

BTW, @ddysher had a talk on KubeCon and I think he may have no time these days.

**Comment by YujiOshima** [comment]
＠gaocegege Thank you!
OK, we can wait for his review,
And I'm going to address @libbyandhelen 's comments.

**Comment by gaocegege** [comment]
Hi @YujiOshima 

ddysher may be busy, I think. And we could merge it and go ahead if you think it blocks your work.

**Comment by YujiOshima** [comment]
@gaocegege Thanks. Yes, This block some work.
I will push a new commit applied  @libbyandhelen 's comments soon.
Then please review.

**Comment by gaocegege** [comment]
:ok_hand:

**Comment by YujiOshima** [comment]
I update
* You can get worker_ids from study ID, trial ID or worker ID.
* You can get suggestion/earlystopping parameter list from study ID.
* Trials are created in suggestion service.

@gaocegege PTAL

**Comment by gaocegege** [comment]
Cool I will take a look.

**Comment by YujiOshima** [comment]
Is the test working? 🤔

**Comment by YujiOshima** [comment]
@gaocegege @jlewi I'm not sure why the test goes time-out. Do you have any ideas?

**Comment by ddysher** [comment]
Thanks!  Generally LGTM :+1:

**Comment by YujiOshima** [comment]
Yes, we can merge this!

**Pull request merged**
