### PR TITLE
mini fix when update experiment/trial instance

### PR DESCRIPTION
**Pull request by hougangliu**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/470)

### CODE REVIEW

**Comment by johnugeorge** [comment]
@ho Why is this needed? We need to just update the status

**Comment by hougangliu** [comment]
> @hougangliu Why is this needed? We need to just update the status

Per my test, before this PR, experiment update always fails.

**Comment by johnugeorge** [comment]
Did you add status as a subresource in CRD

**Comment by hougangliu** [comment]
> Did you add status as a subresource in CRD

Ok, close this PR.

**Pull request closed without merging**
