### PR TITLE
Add Changelog for Katib v0.16.0-rc.0

### PR DESCRIPTION
**Pull request by andreyvelich**
I added Changelog for Katib v0.16.0-rc.0

I identify a few **Breaking Changes.**

Thanks everyone for your contributions!

Please take a look.

/cc @tenzen-y @johnugeorge @gaocegege @elenzio9 @droctothorpe @nagar-ajay @orfeas-k 
cc @kubeflow/release-team

### CODE REVIEW

**Comment by tenzen-y** [comment]
Looks good! Thanks!
/lgtm

**Comment by andreyvelich** [comment]
Let's merge it.
/hold cancel

**Pull request merged**
