### PR TITLE
Add prometheus scraping and grafana support to charmed katib-controller operator

### PR DESCRIPTION
**Pull request by jardon**
**What this PR does / why we need it**:
These changes add support for prometheus scraping and providing a grafana dashboard to the charmed katib-controller operator.  With the changes you can do the following to connect the applications and enable scraping:
```bash
juju relate prometheus-k8s katib-controller
juju relate grafana-k8s katib-controller
```

**Checklist:**

- [X] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Review by Arhell — COMMENTED** [review]
/ok-to-test

**Comment by ca-scribner** [comment]
I think this just failed because the github runner was particularly slow.  Not sure how to get the tests to rerun though

**Comment by gaocegege** [comment]
I rerun the jobs manually.

**Comment by ca-scribner** [comment]
ty!  We bumped the timeout on the flaky test too so it shouldn't fail like it did before.  This should be good to go now

**Comment by johnugeorge** [comment]
@ca-scribner Can you lgtm this PR if it is ready to be merged?

**Review by ca-scribner — APPROVED** [review]

**Pull request merged**
