### PR TITLE
Add the license to pbt

### PR DESCRIPTION
**Pull request by tenzen-y**
Signed-off-by: tenzen-y <yuki.iwai.tz@gmail.com>

**What this PR does / why we need it**:
I added the license to PBT.

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by tenzen-y** [comment]
@kubeflow/wg-automl-leads PTAL.

**Review by gaocegege — COMMENTED** [review]
/lgtm
/approve

**Comment by a9p** [comment]
Hey @tenzen-y & @gaocegege! I originally excluded the KF copyright on this file since it is heavily based on / copied from the Ray implementation [here](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/pbt_example.py). I defer to your expertise, but wanted to surface this point in the event it necessitates changing anything!

**Comment by tenzen-y** [comment]
> Hey @tenzen-y & @gaocegege! I originally excluded the KF copyright on this file since it is heavily based on / copied from the Ray implementation [here](https://github.com/ray-project/ray/blob/master/python/ray/tune/examples/pbt_example.py). I defer to your expertise, but wanted to surface this point in the event it necessitates changing anything!

@a9p Thanks for your response!
We have created other trial images based on other codes as well as the simple-pbt and added the KF copyright to all trial images.
So we need to add the KF copyright to the simple-pbt.

Although, we might be able to add readme, same as other trial images such as the [tf-mnit-with-summaries](https://github.com/kubeflow/katib/blob/293a78575fdaf2188c2aeff877909725687cce18/examples/v1beta1/trial-images/tf-mnist-with-summaries/README.md) since it would be good to clarify that the simple-pbt is heavily based on from Ray.

WDYT?

**Pull request merged**
