### PR TITLE
Add .travis.yml to check build and coverage

### PR DESCRIPTION
**Pull request by lkpdn**
[SUGGESTION]
This is the 3rd TODO listed in #258. I'd appreciate your thought about this. Thanks.
 
Note:
need to activate this repo on Travis CI + Coveralls.io beforehand, then fill in env.global[0].secure part. Until then, this should never be merged.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/262)

### CODE REVIEW

**Comment by YujiOshima** [comment]
@lkpdn Please exprain why need travis. Currently CI env is not enough? IMHO, it is difficult to understand..
/cc @richardsliu @jlewi

**Comment by lkpdn** [comment]
@YujiOshima The reason I chose travis is just that it looked easy and popular way of running goveralls. I'm not sure what "CI env" is, could you please let me know how to run goveralls with "CI env"?

**Comment by toshiiw** [comment]
@lkpdn could you try in your forked repo and  show how a coverage report will look like?

**Comment by lkpdn** [comment]
@toshiiw i've activated Travis + Coveralls for my forked repo. Note that ${GOPATH}/src/github.com/lkpdn should be ${GOPATH}/src/github.com/kubeflow so it fails in the last "script" stage.
https://travis-ci.org/lkpdn/katib/builds/461548111

**Comment by lkpdn** [comment]
@gaocegege Thanks for your comment.
@YujiOshima @richardsliu @jlewi Please let me hear your thought on this. I'm ok whether or not we use travis, while I'm not sure how we do that in our own CI so I cannot cook up a PR.

**Comment by jlewi** [comment]
I enabled travis and coveralls

But like @gaocegege it would be better to try to follow whatever Kubernetes does for test coverage.

**Comment by lkpdn** [comment]
@jlewi thanks. You mean this part https://github.com/kubernetes/kubernetes/blob/d15895229360b8a48abe56e19fcfeb5c2bf0c26e/hack/make-rules/test.sh#L293-L357 ?

**Comment by lkpdn** [comment]
This PR now seems useless so let me close this.

**Pull request closed without merging**
