### PR TITLE
Upload python SDK version

### PR DESCRIPTION
**Pull request by andreyvelich**
I uploaded new 0.0.4 version to PyPi with latest updated API.
Also make few fix in docs to make it easier to read.

### CODE REVIEW

**Comment by andreyvelich** [comment]
I have updated Katib client with `get_suggestion()` function and upload new version (0.0.5) to PyPi.
Since we removed import `KatibClient` in the main `__init__.py` [here](https://github.com/kubeflow/katib/pull/1252/files#diff-2d8346db5e344cb76f082e4183a66bf6L25-L30), in the new examples users should import client like this:
`from kubeflow.katib.api.katib_client import KatibClient`.
I will submit new examples for v1beta1 in the follow PR.

/cc @jinchihe @gaocegege @johnugeorge

**Comment by andreyvelich** [comment]
After talking with @jinchihe, we decided to add `from kubeflow.katib.api.katib_client import KatibClient` to the `__init__.py`.

It makes easier to user our SDK for the user and be consistent with other Kubeflow SDKs.

**Comment by gaocegege** [comment]
Do you mean we will add it back to init.py?

**Comment by andreyvelich** [comment]
> Do you mean we will add it back to init.py?

@gaocegege Yes, I updated post-gen script to add this line: https://github.com/kubeflow/katib/pull/1335/files#diff-a856775ac78804af016b992a7ef29e4fR21

**Comment by jinchihe** [comment]
/lgtm

@andreyvelich Looks great! By the way, do you have any plan to add a sample for the SDK Client? Thanks.

**Comment by andreyvelich** [comment]
> /lgtm
> 
> @andreyvelich Looks great! By the way, do you have any plan to add a sample for the SDK Client? Thanks.

I have already created PR with examples for v1beta1: https://github.com/kubeflow/katib/pull/1337.

**Review by andreyvelich — COMMENTED** [review]
/approve

**Pull request merged**
