### PR TITLE
[bugfix]: increase test timeout

### PR DESCRIPTION
**Pull request by anencore94**
**What this PR does / why we need it**:
- It might fix unit test fail issue described in #1649

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
#1649

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Review by andreyvelich — COMMENTED** [review]
@anencore94 Thank you for taking this!
Are you sure that increasing timeout will help to avoid flaky unit tests ?

For example in this failed test: https://github.com/kubeflow/katib/runs/3523610062?check_suite_focus=true.
Trial status was updated to `Metrics Unavailable`, but tests were failed on the [previous step](https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/trial/trial_controller_test.go#L254-L261), where we compare observation results.

I think to fix it, we might need to split running Experiments in the different unit tests.

For example, currently in the [`TestReconcileBatchJob`](https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/trial/trial_controller_test.go#L89) we run 3 Experiments: 
1. Trial run with "Failed" BatchJob
2. Trail with "Complete" BatchJob and Available metrics.
3. Trail with "Complete" BatchJob and Unavailable metrics.

Maybe we should split it in 3 different unit tests with separate test managers.

WDYT @anencore94 @gaocegege @johnugeorge ?

**Review by gaocegege — COMMENTED** [review]
/lgtm
/approve

**Comment by gaocegege** [comment]
Sorry for the quick merge.

I think we can increase it and see If it works. In the best case, we should split the test cases. Should we create an issue for it?

**Comment by andreyvelich** [comment]
No worries @gaocegege :)
Yes, let's continue the discussion under https://github.com/kubeflow/katib/issues/1649.

**Pull request merged**
