### PR TITLE
Update Changelog for Katib v0.13.0-rc.0 release

### PR DESCRIPTION
**Pull request by andreyvelich**
I updated Changelog for Katib `0.13.0-rc.0` release.

I combined our work in these sections:

```
New Features
  Algorithms and Components
  UI Features
Documentation
Bug Fixes
Misc
```

Please let me know what do you think about it ?

/cc @gaocegege @johnugeorge @tenzen-y @anencore94 @knkski @kimwnasptd @terrytangyuan @seong7 @eliaskoromilas @DnPlas @DomFleischmann @henrysecond1 @alexeykaplin @haoxins @midhun1998 @ca-scribner 

cc @jbottum  

/hold for the review

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
Thank you for these updates @andreyvelich !
/lgtm

**Review by terrytangyuan — APPROVED** [review]
Looks great!

**Review by anencore94 — COMMENTED** [review]
I think it looks better too :)

**Comment by andreyvelich** [comment]
Thanks everyone for the review!
/hold cancel

**Pull request merged**
