### PR TITLE
Use kubeflowkatib repo as image repo of example

### PR DESCRIPTION
**Pull request by hougangliu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/949)

### CODE REVIEW

**Comment by johnugeorge** [comment]
@richardsliu @hougangliu Should we keep these images in gcr or docker repository?

**Comment by hougangliu** [comment]
Per talk by slack channel, for now we cannot have push permission for grc repository for example images. so we use `kubeflowkatib` docker hub for example images

**Pull request merged**
