### PR TITLE
Refactor Kustomize manifests for Katib

### PR DESCRIPTION
**Pull request by andreyvelich**
I refactored Kustomize manifest for Katib.
I followed this approach:
1. All Katib manifests are located in `/components`.
2. All installs with kustomization files are located in `/installs`.

User can select required install Kustomize file, e.g. Katib standalone, Kubeflow, IBM, etc..
User also are able to use pure `kubectl` to deploy Katib, we can extend `deploy.sh` script for that later.

We can keep the `latest` tag for the Katib standalone installation and we can add Katib 0.11 tag for the Kubeflow Katib installation.

For the Katib config I added `patchesStrategicMerge` to the Kustomize file. I am not sure if it is possible to modify image tags in the other way.

For the Kubeflow installation I added: 
```
commonLabels:
  app.kubernetes.io/component: katib
```
I left only 1 application with this label for the Katib component.

Please take a look @yanniszark.

I am still updating some docs in this PR.

/cc @gaocegege @johnugeorge

### CODE REVIEW

**Comment by andreyvelich** [comment]
I changed docs in the Katib repo.
/hold for the reviews

**Comment by andreyvelich** [comment]
@DomFleischmann @knkski @RFMVasconcelos I disabled GitHub actions at this PR, since we should fix: https://github.com/kubeflow/katib/issues/1453 and add cert-generator to generator certs.
If you check logs from the controller: https://github.com/kubeflow/katib/pull/1464/checks?check_run_id=2080590497, manager fails because `/tmp/cert/tls.crt` file doesn't exist.

**Comment by andreyvelich** [comment]
I also updated tags for the Trial images to `v1beta1-c6c9172` for these changes: https://github.com/kubeflow/katib/pull/1457.

**Comment by yanniszark** [comment]
@andreyvelich to explore the diff, I built:
- `manifests/v1beta1/installs/katib-standalone` on master
- `manifests/v1beta1/installs/katib-with-kubeflow` on this branch

I'm uploading the old and new yaml, for completeness:
[old.yaml.log](https://github.com/kubeflow/katib/files/6124561/old.yaml.log)
[new.yaml.log](https://github.com/kubeflow/katib/files/6124562/new.yaml.log)

The main diff I saw is:
- The new YAML has the webhook configurations. Nice!
- The new YAML has the cert-generator script. Also nice, it would be good if we could somehow make it optional. But we can discuss later on this.
- The new YAML creates the following PersistentVolume:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app.kubernetes.io/component: katib
    type: local
  name: katib-mysql
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /tmp/katib
  storageClassName: katib
```
I don't think it's right to include a PersistentVolume, as it ties Katib installation to a particular type of storage (hostPath). It also presumes the existence of the Katib storageclass. By including just a PersistentVolumeClaim, we make storage pluggable. It's standard to include a PVC (not a PV) in other manifests as well. What do you think?

**Comment by andreyvelich** [comment]
Thank you for the review @yanniszark!
> The new YAML has the cert-generator script. Also nice, it would be good if we could somehow make it optional. But we can discuss later on this.

I think in the next release (~ Katib 0.11.1 or Katib 0.12 ) we can make it optional. We should have a discussion how we can do it (cert-manager overlay for instance).


> I don't think it's right to include a PersistentVolume, as it ties Katib installation to a particular type of storage (hostPath). It also presumes the existence of the Katib storageclass. By including just a PersistentVolumeClaim, we make storage pluggable. It's standard to include a PVC (not a PV) in other manifests as well. What do you think?

We can exclude this PV from the Kubeflow installation.
Before the manifest migration, PV was included in the Katib installation, but PV was excluded in the Kubeflow installation.
We have seen a lot of problems when users use their own StorageClass to provision volume (https://github.com/kubeflow/katib/issues/1415, https://github.com/kubeflow/katib/issues/1156, https://github.com/kubeflow/katib/issues/1212, etc.)
That is why we included PV with `hostPath` in the Katib installation by default.

If users know that cluster Storage Class can properly provision volume, they can always modify the kustomization file.

WDYT @yanniszark ? cc @gaocegege @johnugeorge

**Comment by yanniszark** [comment]
> We have seen a lot of problems when users use their own StorageClass to provision volume (#1415, #1156, #1212, etc.)
> That is why we included PV with hostPath in the Katib installation by default.

Thanks for including the related issues for context! I agree that it's good to try and make users' life easier. Since creating the PV is essentially an environment setup step (and may have security implications because it's using a hostPath volume, thus having side-effects on the host machine), I would include it in a separate manifest and add an optional step to install it.

For this PR, excluding it in the Kubeflow overlay seems ok. I'd like to open the discussion in the future if you agree!

**Comment by andreyvelich** [comment]
> Thanks for including the related issues for context! I agree that it's good to try and make users' life easier. Since creating the PV is essentially an environment setup step (and may have security implications because it's using a hostPath volume, thus having side-effects on the host machine), I would include it in a separate manifest and add an optional step to install it.

> For this PR, excluding it in the Kubeflow overlay seems ok. I'd like to open the discussion in the future if you agree!

Sure, it makes sense. Let's keep for the Kubeflow 1.3 release as it was before (Katib installation - PV is included, Kubeflow installation - PV is excluded). I will create an issue and we can discuss how we want to manager it in the further release.

**Comment by andreyvelich** [comment]
@yanniszark Also what do you think about this patch:
https://github.com/kubeflow/katib/blob/585c01df7e3991a119d27a855a9d9a7ba9906e6d/manifests/v1beta1/installs/katib-with-kubeflow/kustomization.yaml#L49-L111

Does it sound good for you ?

**Comment by yanniszark** [comment]
> Does it sound good for you ?

Yes, unfortunately you need to patch the whole ConfigMap :/
You can also use the `configMapGenerator` with behavior merge:
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/

**Comment by andreyvelich** [comment]
I believe `configMapGenerator` will add hash once it generates resource which doesn't work for us currently.
Let's continue with Patch for now.

@yanniszark If you are fine with other changes, please can you give your `lgtm` and we can move forward.

**Comment by andreyvelich** [comment]
@yanniszark I was actually thinking about the patch more.
Since we try to follow release process as you mentioned here: https://github.com/kubeflow/katib/issues/1466, we don't need to have specific image tag in the `katib-with-kubeflow` install.

Thus, we can use [re-use patch](https://github.com/kubeflow/katib/blob/c7027143f8adf7085046c33b05cd6dbfed3b57f8/manifests/v1beta1/installs/katib-with-kubeflow/kustomization.yaml#L49) for the Katib config and simplify kustomization files.

**Comment by andreyvelich** [comment]
@gaocegege @johnugeorge I changed mxnet example to get MNIST data using mxnet API as described in [MXNet docs](https://mxnet.apache.org/versions/1.7.0/api/python/docs/tutorials/packages/gluon/image/mnist.html#Loading-Data).
As I can see downloading data from http://yann.lecun.com/exdb/mnist/ is impossible currently.

**Comment by andreyvelich** [comment]
I changed MNIST dataset to FashionMNIST for Pytorch MNIST example.
I am not sure once http://yann.lecun.com/exdb/mnist/ become stable.
/hold cancel

**Pull request merged**
