### PR TITLE
StudyJobController: Update worker status and fix status bug

### PR DESCRIPTION
**Pull request by YujiOshima**
* Update worker status in StudyJob controller
* Mark worker complete after the metrics are reported.

/assign @gaocegege

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/159)

### CODE REVIEW

**Comment by gaocegege** [comment]
Sorry for the delay.

Is it ready to merge?

**Comment by YujiOshima** [comment]
@gaocegege Sorry, please wait. I found some bugs in this PR. I will update soon.

**Comment by gaocegege** [comment]
Sure, feel free to @ me

**Comment by YujiOshima** [comment]
@gaocegege Thank you for waiting! I updated it. We can merge it.

**Pull request merged**
