### PR TITLE
Remove MXNet examples

### LINKED ISSUE #2261: Remove MXNet example
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Since the MXNet was made archive, the MXNet dataset was removed in the following.
So, we need to remove our MXNet example and then switch CI and examples with MXNet to another framework.

```shell
root@2a88f8620665:/opt/mxnet-mnist# python mnist.py 
2024-02-20T05:39:55Z INFO     start with arguments Namespace(num_classes=10, num_examples=60000, add_stn=False, image_shape='1, 28, 28', network='mlp', num_layers=None, gpus=None, kv_store='device', num_epochs=10, lr=0.05, lr_factor=0.1, lr_step_epochs='10', initializer='default', optimizer='sgd', mom=0.9, wd=0.0001, batch_size=64, disp_batches=100, model_prefix=None, save_period=1, monitor=0, load_epoch=None, top_k=0, loss='', test_io=0, dtype='float32', gc_type='none', gc_threshold=0.5, macrobatch_size=0, warmup_epochs=5, warmup_strategy='linear', profile_worker_suffix='', profile_server_suffix='', use_imagenet_data_augmentation=0)
2024-02-20T05:39:55Z DEBUG    Starting new HTTP connection (1): data.mxnet.io:80
2024-02-20T05:39:55Z DEBUG    http://data.mxnet.io:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 301 290
2024-02-20T05:39:55Z DEBUG    Starting new HTTP connection (1): data.mxnet.io.s3-website-us-west-1.amazonaws.com:80
2024-02-20T05:39:55Z DEBUG    http://data.mxnet.io.s3-website-us-west-1.amazonaws.com:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 403 303
download failed, retrying, 4 attempts left
2024-02-20T05:39:55Z DEBUG    Starting new HTTP connection (1): data.mxnet.io:80
2024-02-20T05:39:55Z DEBUG    http://data.mxnet.io:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 301 290
2024-02-20T05:39:55Z DEBUG    Starting new HTTP connection (1): data.mxnet.io.s3-website-us-west-1.amazonaws.com:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io.s3-website-us-west-1.amazonaws.com:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 403 303
download failed, retrying, 3 attempts left
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 301 290
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io.s3-website-us-west-1.amazonaws.com:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io.s3-website-us-west-1.amazonaws.com:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 403 303
download failed, retrying, 2 attempts left
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 301 290
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io.s3-website-us-west-1.amazonaws.com:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io.s3-website-us-west-1.amazonaws.com:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 403 303
download failed, retrying, 1 attempt left
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io:80
2024-02-20T05:39:56Z DEBUG    http://data.mxnet.io:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 301 290
2024-02-20T05:39:56Z DEBUG    Starting new HTTP connection (1): data.mxnet.io.s3-website-us-west-1.amazonaws.com:80
2024-02-20T05:39:57Z DEBUG    http://data.mxnet.io.s3-website-us-west-1.amazonaws.com:80 "GET /data/mnist/train-labels-idx1-ubyte.gz HTTP/1.1" 403 303
Traceback (most recent call last):
  File "/opt/mxnet-mnist/mnist.py", line 86, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "/opt/mxnet-mnist/common/fit.py", line 185, in fit
    (train, val) = data_loader(args, kv)
  File "/opt/mxnet-mnist/mnist.py", line 44, in get_mnist_iter
    mnist = mx.test_utils.get_mnist()
  File "/usr/local/lib/python3.10/site-packages/mxnet/test_utils.py", line 1906, in get_mnist
    (train_lbl, train_img) = read_data(
  File "/usr/local/lib/python3.10/site-packages/mxnet/test_utils.py", line 1894, in read_data
    with gzip.open(mx.test_utils.download(label_url)) as flbl:
  File "/usr/local/lib/python3.10/site-packages/mxnet/test_utils.py", line 1812, in download
    raise e
  File "/usr/local/lib/python3.10/site-packages/mxnet/test_utils.py", line 1803, in download
    assert r.status_code == 200, "failed to open %s" % url
AssertionError: failed to open http://data.mxnet.io/data/mnist/train-labels-idx1-ubyte.gz
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Related to:
- #2259

---

Love this feature? Give it a 👍 We prioritize the features with the most 👍

### PR DESCRIPTION
**Pull request by tenzen-y**
**What this PR does / why we need it**:
I removed MXNet example and then, I replaced MXNet with PyTorch in examples, and test data.

This PR is blocking all PRs since this PR fixed the current stopped-working CI.
Blocked:

- #2266 
- #2252
- https://github.com/kubeflow/manifests/pull/2637
- #2248 

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #2261 

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by tenzen-y** [comment]
Ready for the review.

/assign @andreyvelich @johnugeorge

**Comment by johnugeorge** [comment]
/lgtm

Thanks @tenzen-y

**Pull request merged**
