### PR TITLE
Make test fields private in Go unit tests

### PR DESCRIPTION
**Pull request by tariq-hasan**
**What this PR does / why we need it**:

Following the [suggestion](https://github.com/kubeflow/katib/pull/2289#discussion_r1566264061) to keep the test fields private within Go unit tests, this PR implements the necessary changes.

The unit tests for Go have been run and validated in [this CI Workflow](https://github.com/tariq-hasan/katib/actions/runs/8840443938).

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by tariq-hasan** [comment]
I wonder if we should re-run [Unit Test 1.27.1](https://github.com/kubeflow/katib/actions/runs/8840749744/job/24277532658?pr=2316) given that this issue was flagged before in [other PRs](https://github.com/kubeflow/katib/pull/2285#issuecomment-2033391949) and jobs were restarted.

Other jobs look to be okay.

I was also wondering if a dedicated issue needs to be opened to look into this.

**Comment by tariq-hasan** [comment]
I also wanted to note that the following fails in `darwin/arm64` architecture due to https://github.com/kubeflow/katib/blob/master/go.mod#L3 and is fixed by https://github.com/golang/go/issues/65568#issuecomment-1954876836. Does this require an update to `go.mod` in the `katib` repo? Or does `darwin/arm64` fall outside the list of supported architectures for `katib`?

```
tariqhasan@Tariqs-MacBook-Air katib % make test ENVTEST_K8S_VERSION=1.27.1 # or any other K8s version
KUBEBUILDER_ASSETS="" go test ./pkg/... ./cmd/... -coverprofile coverage.out
go: downloading go1.22 (darwin/arm64)
go: download go1.22 for darwin/arm64: toolchain not available
make: *** [test] Error 1
```

**Comment by tenzen-y** [comment]
> I wonder if we should re-run [Unit Test 1.27.1](https://github.com/kubeflow/katib/actions/runs/8840749744/job/24277532658?pr=2316) given that this issue was flagged before in [other PRs](https://github.com/kubeflow/katib/pull/2285#issuecomment-2033391949) and jobs were restarted.
> 
> Other jobs look to be okay.
> 
> I was also wondering if a dedicated issue needs to be opened to look into this.

@tariq-hasan I tried to re-run 5 times, but that case never succeeded in CI...
In your local, what happened?

**Comment by tenzen-y** [comment]
> > I wonder if we should re-run [Unit Test 1.27.1](https://github.com/kubeflow/katib/actions/runs/8840749744/job/24277532658?pr=2316) given that this issue was flagged before in [other PRs](https://github.com/kubeflow/katib/pull/2285#issuecomment-2033391949) and jobs were restarted.
> > Other jobs look to be okay.
> > I was also wondering if a dedicated issue needs to be opened to look into this.
> 
> @tariq-hasan I tried to re-run 5 times, but that case never succeeded in CI... In your local, what happened?

After I restarted it 6 times, that case succeeded. That case is so flaky...

**Comment by tenzen-y** [comment]
> I was also wondering if a dedicated issue needs to be opened to look into this.

Actually, we already have a dedicated issue: https://github.com/kubeflow/katib/issues/2269

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm
/approve

**Pull request merged**
