### PR TITLE
Improve Katib README

### PR DESCRIPTION
**Pull request by PatrickXYS**
Related: #1332.
I will debug the infra in this PR.

- [x] This is the PR to see if we can trigger AWS Presubmit.
- [x] This is the PR to see if Github UI integrate aws-kf-ci-bot

### CODE REVIEW

**Comment by Jeffwan** [comment]
@PatrickXYS Seems only `k8s-ci-bot` create the job?

**Comment by PatrickXYS** [comment]
Weird, let me retry

**Comment by PatrickXYS** [comment]
image

It actually suffices

**Comment by PatrickXYS** [comment]
It disappear again...

**Comment by PatrickXYS** [comment]
image

Put here as reference

**Comment by PatrickXYS** [comment]
@andreyvelich  It's good to go, can you lgtm and approve, let's monitor if Tide works properly

**Review by andreyvelich — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
