### PR TITLE
Print verbose error when studyjob updates fail

### PR DESCRIPTION
**Pull request by toshiiw**
This is to test the scenario behind kubeflow/katib/pull/411

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/417)

### CODE REVIEW

**Comment by toshiiw** [comment]
I realized studyjobcontroller logs should be collected, if we are going to test in the CI.

**Comment by gaocegege** [comment]
/close

Thanks for the PR. But we already dropped v1alpha1. We can't merge it since v1alpha1 is deprecated.

**Comment by gaocegege** [comment]
/close

Thanks for the PR. But we already dropped v1alpha1. We can't merge it since v1alpha1 is deprecated.

**Pull request closed without merging**
