### PR TITLE
Enrich GUI

### PR DESCRIPTION
**Pull request by YujiOshima**
* Allow finding status of Studyjobs.
* Allow to manage worker template and create studyjob from UI.

katibui-demo

/cc @richardsliu

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/264)

### CODE REVIEW

**Comment by richardsliu** [comment]
@YujiOshima 
This looks great. Can you update the paths of the static files to the new relative path? There are also some conflicts.

**Comment by YujiOshima** [comment]
@richardsliu Thank you! I updated PTAL.

**Comment by YujiOshima** [comment]
@richardsliu Thank you for your comments. Fixed.

**Pull request merged**
