### PR TITLE
Verify that Trials were successfully deleted

### PR DESCRIPTION
**Pull request by andreyvelich**
When I tried to update `parallelTrialCount` to less value, I got errors in controller.

In `deleteTrials` we should verify that Trials were successfully deleted before running reconcile loop again and update suggestion `requests` and `status.suggestions`.

Otherwise, [`updateTrialsSummary`](https://github.com/andreyvelich/katib/blob/04d78c24e47c6fe951099c5e5353bc79ecadc5af/pkg/controller.v1beta1/experiment/util/status_util.go#L55) is resynchronized with Trial list and `addCount` for [`ReconcileSuggestion`](https://github.com/andreyvelich/katib/blob/04d78c24e47c6fe951099c5e5353bc79ecadc5af/pkg/controller.v1beta1/experiment/experiment_controller.go#L458) is incorrect.

/assign @gaocegege @johnugeorge

### CODE REVIEW

**Comment by andreyvelich** [comment]
I updated test, unit tests locally works good, I don't know why it fails sometime in CI.

@gaocegege @johnugeorge @sperlingxx Do you have any ideas why we have 2 Travis in our pre-submits and post-submits?
First is on travis-ci.org https://travis-ci.org/github/kubeflow/katib/builds.
Second is on travis-ci.com https://travis-ci.com/github/kubeflow/katib/builds.

**Comment by andreyvelich** [comment]
Should we disable Katib on [`travis-ci.org`](https://travis-ci.org/organizations/kubeflow/repositories) since it is outdated: https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps ?

**Comment by gaocegege** [comment]
> Should we disable Katib on travis-ci.org since it is outdated: https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps ?

SGTM

BTW, I am not sure if I understand the PR, can you give me an example about why we need it?

**Comment by andreyvelich** [comment]
@gaocegege If you tried to edit Experiment, e.g change parallelTrialCount from 4 to 2, 2 Trial has to be deleted.
Here we execute `Delete`: https://github.com/kubeflow/katib/blob/9cf45448e40cff0d558e2266a659091bd06e8e44/pkg/controller.v1beta1/experiment/experiment_controller.go#L389
After that, k8s objet will not be deleted immediately, finalizers run after Trial deletion, because of that I added check before finish Experiment reconciler. 
If we don't do it, on the next Experiment reconciler loop `List`:
https://github.com/kubeflow/katib/blob/9cf45448e40cff0d558e2266a659091bd06e8e44/pkg/controller.v1beta1/experiment/experiment_controller.go#L266 
returns Trial list with 2 deleting Trials.
Then, `UpdateExperimentStatus` overrides Experiment status incorrect:
https://github.com/kubeflow/katib/blob/9cf45448e40cff0d558e2266a659091bd06e8e44/pkg/controller.v1beta1/experiment/experiment_controller.go#L271.
And `addCount` will be not correct:
https://github.com/kubeflow/katib/blob/9cf45448e40cff0d558e2266a659091bd06e8e44/pkg/controller.v1beta1/experiment/experiment_controller.go#L315.

Suggestion status also needs to be updated since we store Trials assignment there.

**Comment by andreyvelich** [comment]
@jlewi Could help us to disable travis-ci.org for Katib, please?
I don't have permission to disable travis-ci.org from here: https://travis-ci.org/organizations/kubeflow/repositories or from Katib repo settings.

**Pull request merged**
