### PR TITLE
Remove istio sidecar annotation from all examples

### PR DESCRIPTION
**Pull request by andreyvelich**
Related: https://github.com/kubeflow/katib/issues/1214.

I added `sidecar.istio.io/inject: "false"` to all examples.
Since we support custom CRD that should be added manually.

### CODE REVIEW

**Comment by andreyvelich** [comment]
After discussion with @johnugeorge, we decided to delete istio annotation from the examples.
It makes easier for the user to read the example and this change requires only if Istio is used.

We should update documentation with this information, like we did for [PyTorch Job](https://www.kubeflow.org/docs/components/hyperparameter-tuning/hyperparameter/#pytorch-example).

/cc @gaocegege

**Review by gaocegege — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
