### PR TITLE
Update mysql version mysql:8.0.15

### PR DESCRIPTION
**Pull request by toniz**
New version of mysql installation fails.  I make a test on  mysql:8.0.16 mysql:8.0.17 mysql:8.0.18. All Failed.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/988)

### CODE REVIEW

**Comment by gaocegege** [comment]
Can you explain more about the failure? Did it fail when building the image or running?

**Comment by toniz** [comment]
> Can you explain more about the failure? Did it fail when building the image or running?
```
xwj@master01:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:41:55Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
```
2020-01-02T02:51:46.211578Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
2020-01-02T02:51:46.211734Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.17) starting as process 1
2020-01-02T02:51:54.409059Z 0 [ERROR] [MY-011947] [InnoDB] Cannot open '/var/lib/mysql/datadir/ib_buffer_pool' for reading: No such file or directory
2020-01-02T02:51:55.407300Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2020-01-02T02:51:55.433703Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2020-01-02T02:51:55.475134Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.17'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
2020-01-02T02:51:55.567273Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
```

The pod is created. but the root password is not set.  entrypoint.sh may have some problem.

**Comment by toniz** [comment]
> Can you explain more about the failure? Did it fail when building the image or running?

My test file:
secrets.yaml
```
apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: dGVzdA==
kind: Secret
metadata:
  name: katib-db-secrets
type: Opaque
```
pvc.yaml;
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
  name: katib-mysql-1
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rbd
  volumeMode: Filesystem
```
deployment.yaml
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-db
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-db-version
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
          app: test-db-version
      creationTimestamp: null
      name: test-db
    spec:
      containers:
      - args:
        - --datadir
        - /var/lib/mysql/datadir
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: katib-db-secrets
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        - name: MYSQL_DATABASE
          value: katib
        image: mysql:8.0.16
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: katib-db
        ports:
        - containerPort: 3306
          name: dbapi
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - mysql -D ${MYSQL_DATABASE} -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: katib-mysql-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: katib-mysql
        persistentVolumeClaim:
          claimName: katib-mysql-1

```

**Comment by toniz** [comment]
ceph rdb provider has something wrong.

**Comment by Utkagr** [comment]
> ceph rdb provider has something wrong.

Hey @toniz Could you describe what was the issue with ceph rdb provider?

**Pull request closed without merging**
