### PR TITLE
Create Optimizer in BO Suggestion only for the first run

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/katib/issues/1039.

In this PR I added `is_first_run` flag.
We must create `Optimizer` instance using `search_space` only for the first `GetSuggestions` call.

/assign @gaocegege @johnugeorge

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/1057)

### CODE REVIEW

**Comment by andreyvelich** [comment]
See comment: https://github.com/kubeflow/katib/issues/1039#issuecomment-586330937

**Comment by andreyvelich** [comment]
@gaocegege Thanks!

**Comment by andreyvelich** [comment]
/hold 
Hold until I test it on long-term experiment

**Comment by andreyvelich** [comment]
After testing BO on big amount of Trials I found few problems.
``
1. Since we are using one `Optimizer` instance during whole experiment, each `GetSuggestion` call will run `tell` method which will add information about all Trials to `Optimizer`. Xi and yi will have duplicate values (See attributes here: https://scikit-optimize.github.io/modules/generated/skopt.Optimizer.html#skopt.Optimizer) which is not correct and slow performance.
To prevent it, I add `recorded_trials` dict, where key = loss value and value = List of Trial Assignment list for this value. Before running `tell` method, I am checking if this information already contains in the dict and I don't run `tell` method for the recorded Trials.

2. We don't need to iterate over trials if count of succeeded Trials is the same. For some cases, Katib controller can run `GetSuggestion` without new succeeded trials (For Example, some trials failed). We don't need to run `tell` method in that situation.

3. I tried to change `ask` method with `n_points=request_number`, see (https://scikit-optimize.github.io/modules/generated/skopt.Optimizer.html#skopt.Optimizer.ask). It indicates how many Trials do we want to create. Unfortunately, after 35 Trials this method takes so much time to run (more than 1 minute). I am not sure how we can fix it. Any thoughts @gaocegege ?

Also, I added few logging prints in BO.

/hold cancel

/cc @johnugeorge

**Comment by andreyvelich** [comment]
According to the first point, instead of map it is easier to have list of recorded trials name, since they are unique.
Just forgot that we send Trial name to the Suggestion.

**Comment by ever-cheng** [comment]
Doesn't SkoptService exist as a singleton instance for the system, to accept all GetSuggestions request?
How can it accept experiment change if it was bound to a fixed base_service?
        if self.is_first_run:
            self.base_service = BaseSkoptService(...)
            ...
            self.is_first_run = False

**Comment by johnugeorge** [comment]
@ever-cheng No. algorithm service is deployed per experiment

**Pull request merged**
