### PR TITLE
Adding error propagation for K8s client creation in KatibClient

### PR DESCRIPTION
**Pull request by akirillov**
**What this PR does / why we need it**:
This PR adds error propagation for K8s client creation in `katib_client.NewClient()`

**Which issue(s) this PR fixes**
If the `Client` creation fails for some reason - the error is silently ignored and Katib UI backend starts normally. However, when a new experiment is submitted from the UI, it results in nil pointer dereference panic because the `Client` has not been initialized.

**Special notes for your reviewer**:
This PR doesn't change any image versions

**Release note**:
```release-note
Fixed nil pointer dereference in `KatibClient`
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/1053)

### CODE REVIEW

**Comment by akirillov** [comment]
@googlebot I signed it!

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Comment by akirillov** [comment]
thanks for the review, @gaocegege!

**Pull request merged**
