### PR TITLE
Set trial completion status only after metric collection

### PR DESCRIPTION
**Pull request by johnugeorge**
Fixes: #615 

Trial status is updated only if trial observation field is updated. (This will be set if metrics are collected)

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/616)

### CODE REVIEW

**Comment by johnugeorge** [comment]
Will wait for review
/hold

**Comment by johnugeorge** [comment]
@gaocegege Shall we clean up requests in tests in a separate PR?

**Comment by gaocegege** [comment]
Ref https://github.com/kubeflow/katib/issues/619

Yeah

**Comment by andreyvelich** [comment]
Yes, that should work for me. 
Thank you @johnugeorge! 
/lgtm

**Pull request merged**
