### PR TITLE
add build and test for suggestion nasrl

### PR DESCRIPTION
**Pull request by hougangliu**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/401)

### CODE REVIEW

**Comment by andreyvelich** [comment]
@hougangliu Thank you for your PR! Does it fix this issue: https://github.com/kubeflow/katib/issues/400 ?

**Comment by hougangliu** [comment]
> @hougangliu Thank you for your PR! Does it fix this issue: #400 ?

Yes, it can build nas-rl image, too

**Comment by hougangliu** [comment]
Fixes: #400

**Comment by hougangliu** [comment]
/assign @YujiOshima @johnugeorge @richardsliu 
it seems UT machine is under pressures on resource so that kubeflow-katib-presubmit always fails. Before retest when machine comes back, any comment is welcome

**Comment by YujiOshima** [comment]
@hougangliu Thanks! /lgtm

**Pull request merged**
