### PR TITLE
Delete v1alpha1 api

### PR DESCRIPTION
**Pull request by johnugeorge**
V1alpha1 api is no more supported.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/734)

### CODE REVIEW

**Comment by johnugeorge** [comment]
@gaocegege Sure. I will update vendor in a separate PR

**Comment by hougangliu** [comment]
@johnugeorge lgtm but one thing: maybe we should also `dep ensure`

**Comment by hougangliu** [comment]
just found @gaocegege had same comment on vendor, ok for me to update it in a separate PR
/approve

**Pull request merged**
