### PR TITLE
UI: Make KWA's main table responsive and add toolbar

### PR DESCRIPTION
**Pull request by elenzio9**
In this PR:

* Add a top row toolbar with the title of the app and the button to create a new Experiment.
* Replace the card with a responsive table that shows the items. The component also has a paginator.
* Update `Dockerfile` and `README` file to check out to the commit in master branch from the Kubeflow repository that includes the corresponding changes.

Here the new look of the app:
image

Related PR: https://github.com/kubeflow/kubeflow/pull/6316

Signed-off-by: Elena Zioga <elena@arrikto.com>

### CODE REVIEW

**Comment by tenzen-y** [comment]
@kimwnasptd Can you help with reviewing this PR?

/assign @kimwnasptd

**Comment by andreyvelich** [comment]
Thanks a lot for these PRs @elenzio9 !

@elenzio9 @kimwnasptd Please can you confirm that after these changes, users can still use Katib UI standalone without Kubeflow Central Dashboard ?
Ref Issue: https://github.com/kubeflow/katib/issues/1437

**Comment by elenzio9** [comment]
> Thanks a lot for these PRs @elenzio9 !

Your welcome!

> @elenzio9 @kimwnasptd Please can you confirm that after these changes, users can still use Katib UI standalone without Kubeflow Central Dashboard ? Ref Issue: #1437

I guess you're wondering about this part: https://github.com/kubeflow/katib/pull/1982/files#diff-7119d58aceadee83917f133f98cc4e10036ea1a44e09061ed70f406c675d14faR1. I can confirm that the `lib-namespace-select` element, that is the namespace dropdown, is available in standalone mode after these changes. So users will be able to select a namespace if the Kubeflow Central Dashboard is not present.

**Comment by shaowei-su** [comment]
Hi @elenzio9 , it seems that after this PR change the old UI dockerfile can't build locally. Please check the error msg below 

```
> frontend@0.1.0 build /frontend
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve './objectWithoutPropertiesLoose' in '/frontend/node_modules/@babel/runtime/helpers/esm'
Did you mean 'objectWithoutPropertiesLoose.js'?
BREAKING CHANGE: The request './objectWithoutPropertiesLoose' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-11-01T19_28_04_914Z-debug.log
```

could you help take a look? thanks

**Comment by tenzen-y** [comment]
@shaowei-su I fixed `Charmed Katib / Test` in #1987.

**Comment by shaowei-su** [comment]
I see, is the old UI build (https://github.com/kubeflow/katib/tree/master/cmd/ui/v1beta1) fully deprecated now? we unfortunately still rely on it due to the issue we are facing with described here: https://github.com/kubeflow/katib/issues/1967

**Comment by tenzen-y** [comment]
> I see, is the old UI build (https://github.com/kubeflow/katib/tree/master/cmd/ui/v1beta1) fully deprecated now? We unfortunately still rely on it due to the issue we are facing described here: #1967

Yes, we plan to remove the old UI codes for the next katib release.

ref: https://github.com/kubeflow/katib/pull/1984#issuecomment-1292266074

**Comment by shaowei-su** [comment]
Got it, btw @tenzen-y  are you able to reproduce https://github.com/kubeflow/katib/issues/1967?

**Comment by tenzen-y** [comment]
> Got it, btw @tenzen-y are you able to reproduce #1967?

Thanks for reminding me of that.
I replied to that issue.

**Pull request merged**
