### PR TITLE
frontend: Show message in case of uncompleted trial instead of the graph

### PR DESCRIPTION
**Pull request by elenzio9**
In this PR, we implement the following:

- Show message in case of uncompleted trial instead of the graph.
image
- Add some text below the spinner in order to inform users why we're spinning about.
image

### CODE REVIEW

**Review by tenzen-y — COMMENTED** [review]
HI, @elenzio9!
Thanks for this improvement!

Some CI jobs seem to fail, but the errors will be fixed once #2064 is merged with the master branch.

@kimwnasptd Could you help review this PR?

/assign @kimwnasptd

**Comment by elenzio9** [comment]
> HI, @elenzio9! Thanks for this improvement!
> 
> Some CI jobs seem to fail, but the errors will be fixed once #2064 is merged with the master branch.

Your welcome! OK, thanks!

**Comment by tenzen-y** [comment]
@elenzio9 Can you rebase this since we have merged #2064 into the master branch?

**Comment by elenzio9** [comment]
> @elenzio9 Can you rebase this since we have merged #2064 into the master branch?

I just force pushed!

**Comment by orfeas-k** [comment]
The code looks good. I also tested the PR's image and everything works as expected. Thank you @elenzio9 for this improvement!
cc @kimwnasptd 
/lgtm

**Comment by kimwnasptd** [comment]
Thank you for taking a look @orfeas-k!

/lgtm
/approve

**Pull request merged**
