### PR TITLE
[bugfix]: absolute value and typo

### PR DESCRIPTION
**Pull request by anencore94**
Signed-off-by: Jaeyeon Kim <anencore94@gmail.com>
Co-authored-by: Seongjin Kim <seongjinkim1123@gmail.com>

**What this PR does / why we need it**:
image

1) There was a bug when handling odd number of parameters with negative step. For above example, the number of combination should be `64`, not `-62`.
2) minor typo

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by anencore94** [comment]
@googlebot I consent.

**Review by gaocegege — COMMENTED** [review]
/assign @andreyvelich

**Comment by seong7** [comment]
@googlebot I consent.

**Review by andreyvelich — COMMENTED** [review]
Nice catch @anencore94!
/lgtm
/assign @kimwnasptd

**Comment by kimwnasptd** [comment]
The change looks good, thanks @anencore94!

/lgtm

**Pull request merged**
