### PR TITLE
kwa(front): Sort conditions table by timestamp

### PR DESCRIPTION
**Pull request by orfeas-k**
This is a follow-up PR to [this ](https://github.com/kubeflow/kubeflow/pull/6858) and updates the COMMIT file to checkout to the latest KF commit and have the conditions table sorted by timestamp by default.

### CODE REVIEW

**Review by andreyvelich — COMMENTED** [review]
Thank you for this update @orfeas-k!
/assign @kimwnasptd @elenzio9

**Comment by tenzen-y** [comment]
Blocked by: #2070

**Comment by tenzen-y** [comment]
@orfeas-k Can you rebase since we fixed CI?

**Comment by elenzio9** [comment]
@orfeas-k Could you rebase the branch on top of the latest `master` to fix the conflict in the `COMMIT` file?

**Comment by orfeas-k** [comment]
@elenzio9 Just rebased and pushed.

**Comment by orfeas-k** [comment]
I see that a GH action failed although nothing changed in the PR's file in comparison with before the `rebase` I just did. Is there a chance that this GH action is flaky and we need to rerun it? cc @kimwnasptd

**Comment by tenzen-y** [comment]
@orfeas-k Maybe, we can close this PR since we updated the `COMMIT` file to a newer version in https://github.com/kubeflow/katib/pull/2090.

WDYT?

**Comment by orfeas-k** [comment]
@tenzen-y Sure, this makes total sense. Thanks for noticing!

**Pull request closed without merging**
