### PR TITLE
Reconcile trial assignments by comparing suggestion and trials being executed

### LINKED ISSUE #1830: Trials are unrecoverable forever when randomly removes them
/kind bug

**What steps did you take and what happened:**

Created any kind of experiment and run it. 
When I randomly removed the trial created by katib controller, it was unrecoverable forever.

Since the experiment controller reconciles trial assignments by only comparing the number of running trials and desired trials, removed trials can not be recovered.
- https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/experiment/experiment_controller.go#L477-L480

**What did you expect to happen:**

I expect trials should be recovered and completed even if I randomly remove them.

**Anything else you would like to add:**

Uploaded #1831 to fix the problem. Please take a look, thank you.

**Environment:**

- Katib version (check the Katib controller image version): v0.12
- Kubernetes version: (`kubectl version`): v1.19.9
- OS (`uname -a`): 3.10.0-1160.31.1.el7.x86_64

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

### PR DESCRIPTION
**Pull request by henrysecond1**
**What this PR does / why we need it**:

Please see #1830

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:

Fixes #1830 

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by johnugeorge** [comment]
what is the expected behaviour if trials are deleted manually ?  Recreate trial?

**Comment by henrysecond1** [comment]
@johnugeorge 

Thank you for checking!

> what is the expected behaviour if trials are deleted manually ? Recreate trial?

Yes I think trials should be recreated. 
For now, trials are only recreated when we deleted the last created trial.
- https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/experiment/experiment_controller.go#L477-L480

Otherwise, trials are not recreated and also the experiment can not be completed

**Comment by anencore94** [comment]
>> what is the expected behaviour if trials are deleted manually ? Recreate trial?
>
> Yes I think trials should be recreated.

I also agree with @henrysecond1 :) Such situations could happen such as some node crashed on which some trials are scheduled. Trials-controller should be resilient for that case.

**Comment by johnugeorge** [comment]
Just to highlight,  we are assuming that trial names are consistently returned by the suggestion algorithms. 

I think, it is true currently as names are generated by suggestion algorithms.  Is it a valid assumption for all algorithms ?

**Comment by johnugeorge** [comment]
@anencore94 Node crashes are automatically handled as pods will get rescheduled. Did you see different behaviour?

**Comment by johnugeorge** [comment]
@henrysecond1 Can you add a unit test as well?

**Comment by henrysecond1** [comment]
>  @henrysecond1 Can you add a unit test as well?

@johnugeorge

Sure, I added a unit test for `ReconcileSuggestions` that checks whether the function returns missing trial assignments.

**Comment by johnugeorge** [comment]
@tenzen-y Can you also review this PR ?

**Comment by tenzen-y** [comment]
> @tenzen-y Can you also review this PR ?

Sure.

**Review by tenzen-y — COMMENTED** [review]
Thanks for improving the experiment controller algorithm @henrysecond1 !
/lgtm

**Comment by johnugeorge** [comment]
Thanks @henrysecond1 
/approve

**Pull request merged**
