### PR TITLE
Upgrade google/go-containerregistry/pkg/authn/k8schain

### PR DESCRIPTION
**Pull request by tenzen-y**
**What this PR does / why we need it**:

I upgraded `google/go-containerregistry/pkg/authn/k8schain` to avoid the following error with `go get`:

```shell
$ go get
go: github.com/google/go-containerregistry/pkg/authn/k8schain@v0.0.0-20211222182933-7c19fa370dbd requires
        github.com/google/go-containerregistry@v0.5.2-0.20210609162550-f0ce2270b3b4 requires
        github.com/containerd/containerd@v1.5.2 requires
        github.com/Microsoft/hcsshim@v0.8.16 requires
        github.com/containerd/containerd@v1.5.0-beta.4 requires
        github.com/Microsoft/hcsshim@v0.8.15 requires
        github.com/containerd/containerd@v1.5.0-beta.1 requires
        github.com/Microsoft/hcsshim/test@v0.0.0-20201218223536-d3e5debf77da requires
        github.com/docker/distribution@v0.0.0-20190905152932-14b96e55d84c requires
        github.com/mitchellh/osext@v0.0.0-20151018003038-5e2d6d41470f: invalid version: git ls-remote -q origin in /Users/tenzen/go/pkg/mod/cache/vcs/94ed57c5b21c953d93b47487113db43a5c9b69fd990329ec70dc77348c4dd443: exit status 128:
        remote: Repository not found.
        fatal: repository 'https://github.com/mitchellh/osext/' not found
```

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by tenzen-y** [comment]
@andreyvelich @johnugeorge friendly ping :)

**Review by andreyvelich — COMMENTED** [review]
Sorry for the late review @tenzen-y and thanks for the fix
/lgtm
/approve

**Comment by andreyvelich** [comment]
@tenzen-y For some reason I can't re-run the failed action. Please can you push your commit once again ?

**Comment by tenzen-y** [comment]
> @tenzen-y For some reason I can't re-run the failed action. Please can you push your commit once again ?

Oh, I see. I pushed the commit once more.

**Comment by tenzen-y** [comment]
All E2Es with mxnet failed. I guess that our e2e with mxnet is broken. Let me investigate.

**Comment by tenzen-y** [comment]
> All E2Es with mxnet failed. I guess that our e2e with mxnet is broken. Let me investigate.

All PRs are blocked by #2261

**Pull request merged**
