### PR TITLE
[WIP] Add CLI for NAS-Katib system

### PR DESCRIPTION
**Pull request by andreyvelich**
Related to: https://github.com/kubeflow/katib/issues/257.
Fixes: https://github.com/kubeflow/katib/issues/272.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/279)

### CODE REVIEW

**Comment by YujiOshima** [comment]
@andreyvelich Why do we need this CLI? Why not use the only kubectl?

**Comment by andreyvelich** [comment]
@YujiOshima In this CLI we can add additional functional. 
For example, monitoring status of all NAS jobs, show results of NAS job in cmd if you don't want to check it in the UI.

**Comment by YujiOshima** [comment]
It looks similar to this cli https://github.com/kubeflow/katib/tree/master/cmd/cli .
We plan to remove this in the next version since we can do create, delete job by `kubectl` and don't want to manage CLI in this repo.
Do you think we should have our own CLI?

**Comment by andreyvelich** [comment]
@YujiOshima We will make other parts of this system and after that will think about CLI. 
Maybe we will add to this CLI some functionality that kubectl can't provide. 
If not, I will delete this CLI as well. Is it sounds good?

**Comment by YujiOshima** [comment]
@andreyvelich Sounds good! Thank you!

**Pull request closed without merging**
