### PR TITLE
Fix indentation to use spaces (instead of a mix of tabs and spaces)

### PR DESCRIPTION
**Pull request by vinaykakade**
Let me know in case you prefer to use tabs everywhere. But, in general, it is better to use one consistently rather than a mix of both.

### CODE REVIEW

**Comment by gaocegege** [comment]
Thanks for your contribution!

Personally, I like spaces.

**Comment by YujiOshima** [comment]
@vinaykakade Thanks! I also prefer space. 
As the proto files were not formatted by `go fmt`, their style wouldn't be consistent.

**Pull request merged**
