### PR TITLE
add starttime and completiontime to worker

### PR DESCRIPTION
**Pull request by wukong1992**
In order to accurately control the resources, we need to get the start and end time of the worker.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/236)

### CODE REVIEW

**Comment by YujiOshima** [comment]
@wukong1992 That would be nice. Thanks!
/ok-to-test

**Comment by wukong1992** [comment]
@YujiOshima

**Comment by YujiOshima** [comment]
@wukong1992 Thank you!!
/lgtm
/approve

**Pull request merged**
