### PR TITLE
Add the documentation for simple-pbt

### PR DESCRIPTION
**Pull request by tenzen-y**
Signed-off-by: tenzen-y <yuki.iwai.tz@gmail.com>

**What this PR does / why we need it**:
As discussed in [this](https://github.com/kubeflow/katib/pull/1958#issuecomment-1261588102), I added the documentation for the simple-pbt example.

cc: @a9p @gaocegege 

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Review by a9p — APPROVED** [review]
Thanks for following up on the previous issue and adding these changes!

**Comment by johnugeorge** [comment]
Can you rebase

@tenzen-y

**Comment by tenzen-y** [comment]
> Can you rebase
> 
> @tenzen-y

@johnugeorge 
hmm. This PR has been merged into the master branch...

**Pull request merged**
