### PR TITLE
Delete v1alpha2 api

### PR DESCRIPTION
**Pull request by johnugeorge**
v1alpha2 is deprecated. Hence, corresponding files are removed from the repository

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/953)

### CODE REVIEW

**Comment by johnugeorge** [comment]
What can we do about coverage failure? @richardsliu

**Comment by gaocegege** [comment]
I think we could lower the limit about test coverage in coveralls. But I have no permission to do it.

**Pull request merged**
