### PR TITLE
Fix sql syntax for UpdateAlgorithmExtraSettings

### PR DESCRIPTION
**Pull request by hougangliu**
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/633)

### CODE REVIEW

**Comment by gaocegege** [comment]
https://travis-ci.com/kubeflow/katib/builds/114374171#L564

Test failed

**Comment by johnugeorge** [comment]
Just wondering why this bug was not caught in tests earlier.

**Comment by hougangliu** [comment]
> Just wondering why this bug was not caught in tests earlier.

We never execute “update” operation but "insert"

**Pull request merged**
