### PR TITLE
UI: Fix problems

### PR DESCRIPTION
**Pull request by gaocegege**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/786)

### CODE REVIEW

**Comment by johnugeorge** [comment]
Is this in WIP ? Anything blocking this or Shall we merge this with the current changes?

**Comment by johnugeorge** [comment]
@gaocegege

**Comment by gaocegege** [comment]
@johnugeorge Now I hard coded namespace to kubeflow, I think we should fix it. Do you have time on it?

**Comment by gaocegege** [comment]
I think we can merge it then refactor to support customized namespace.

**Comment by johnugeorge** [comment]
> I think we can merge it then refactor to support customized namespace.

@gaocegege Sounds good.

**Pull request merged**
