### PR TITLE
Add Katib release script

### PR DESCRIPTION
**Pull request by andreyvelich**
I added release script to manually push images to `docker.io/kubeflowkatib` registry.
The image tag is `:v1beta1-<commit-SHA>`.
For example:
```
docker.io/kubeflowkatib/katib-controller:v1beta1-d5f5aa0b
```

Once we merge it, I will run the script to update the images.
Related: https://github.com/kubeflow/katib/issues/1367.

As well, I removed legacy release-workflow since we can't use `kubeflow-images-public` more.

/assign @gaocegege @johnugeorge 
/cc @jlewi

### CODE REVIEW

**Comment by PatrickXYS** [comment]
After this PR merged, since Katib is not using Kubeflow Presubmit to release image.

We can also remove from [kubernetes/test-infra ](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/kubeflow-postsubmits.yaml#L148-L160)

**Comment by andreyvelich** [comment]
> After this PR merged, since Katib is not using Kubeflow Presubmit to release image.
> 
> We can also remove from [kubernetes/test-infra ](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubeflow/kubeflow-postsubmits.yaml#L148-L160)

@PatrickXYS Yes, GCP prow post-submit is not needed to Katib more.

**Pull request merged**
