### PR TITLE
chore: Update OWNERS

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

From @jlewi 

> A couple of things to call out for people who have been discussing forming WGs in various areas.
>
>* Please take a look at the roles defined for each WG and think about who you would want to assume those roles
>
>* Please think about ensuring your OWNERs files are up to date and adequately reflect who the OWNERs are for various sub projects. This will be critical to ensuring OWNERs don't get overlooked.

Then we update the OWNERS:

- Remove richardsliu yuji since they are not active in this sub-project
- Add sperlingxx c-bata as reviewers

/cc @johnugeorge @andreyvelich @sperlingxx @c-bata 

Ref https://github.com/kubeflow/community/issues/340

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by c-bata** [comment]
I'm glad to be a reviewer!

/lgtm

**Comment by sperlingxx** [comment]
I'm glad to be a reviewer!

/lgtm

**Comment by gaocegege** [comment]
/approve

Thanks for your contribution! :tada: :+1:

**Pull request merged**
