### PR TITLE
select non-root process by user id instead of parent

### LINKED ISSUE #1383: Skip non-root user processes when waiting for main proces to end
/kind bug

**What steps did you take and what happened:**
Metrics cannot be collected while running trials with Istio enabled. The metrics pod keeps running without sending metrics to the db-manager. After debugging I found out that the function `GetMainProcesses()` waits forever for the Istio sidecar (envoy proxy) to finish. The istio sidecar does not run as root and should therefore be skipped in this proces. The parent process of istio however is the root user (which determines if a process is ran as root). We can check for user id instead of pid parent.

**What did you expect to happen:**
The istio sidecar should not be considered while checking for the main process to be finished.

**Anything else you would like to add:**
I will make a PR with a fix.

**Environment:**

- Kubeflow version 1.0
- Minikube version (`minikube version`):
- Kubernetes version: (use `kubectl version`): 1.18.10
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by robbertvdg**
**What this PR does / why we need it**:
Enables running trials with Istio enabled, and any other process that run as non root.

**Which issue(s) this PR fixes**:
Fixes #1383 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by andreyvelich** [comment]
Thank you for this PR @robbertvdg!

1. If the metrics collector doesn't need to wait until Istio sidecar is finished, have you tried to set 
[`waitAll `](https://github.com/kubeflow/katib/blob/master/cmd/metricscollector/v1beta1/file-metricscollector/main.go#L110) flag to false ? In that case, metrics collector starts after the training process is finished.

2. Do you know why the parent process of the istio sidecar is the root user ? Does some other PID execute the istio sidecar process ?

**Comment by robbertvdg** [comment]
Hi @andreyvelich, the waitAll option seems to be what I need. I am struggling to configure it, do you have an example of how to set it?

> Do you know why the parent process of the istio sidecar is the root user ? Does some other PID execute the istio sidecar process ?
It is about the parent in the process tree of istio. The process parent is `init`, so it is a direct descendent of the startup process.

**Comment by andreyvelich** [comment]
> Hi @andreyvelich, the waitAll option seems to be what I need. I am struggling to configure it, do you have an example of how to set it?

Unfortunately, currently we don't specify [the `-w` flag](https://github.com/kubeflow/katib/blob/master/cmd/metricscollector/v1beta1/file-metricscollector/main.go#L110) in the [`getMetricsCollectorArgs`](https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/pod/inject_webhook.go#L291) for the metrics collector args.

I think, [Katib config](https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/katib-controller/katib-config.yaml#L10) is the good location to set this options for the metrics collector.
Since we already receive some [metrics collector data](https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/pod/inject_webhook.go#L215) from this config.

For example, we can extend [`MetricsCollectorConfig`](https://github.com/kubeflow/katib/blob/master/pkg/util/v1beta1/katibconfig/config.go#L30-L34) with the `WaitAllProcesses` parameter which is `true` or `false`.

It is useful for many use-cases.

What do you think @robbertvdg @gaocegege @johnugeorge  ?

**Comment by robbertvdg** [comment]
I just tested the waitAll option in a fork, and that does the trick! The [MetricsCollectorConfig](https://github.com/kubeflow/katib/blob/master/pkg/util/v1beta1/katibconfig/config.go#L30-L34)  seems like a logical place, since it will be cluster dependent. I will close this MR and the corresponding issue, will you pick up the extension of the config if the others agree to the solution?

**Comment by andreyvelich** [comment]
@robbertvdg It would be great if you can create PR with the updated Config to add this feature in Katib.

What do you think about the parameter name `WaitAllProcesses` @gaocegege @johnugeorge ?

**Comment by robbertvdg** [comment]
@andreyvelich Will do, it will take me a bit longer since i'm not too familiar with the code.

**Comment by andreyvelich** [comment]
@robbertvdg Thank you, no worries. Ping me on [Kubeflow Slack](https://kubeflow.slack.com/archives/DD5SB4Q1M) for any questions/help.

**Pull request closed without merging**
