### PR TITLE
Refactor suggestion services folder structure

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/katib/issues/1144.

- I moved all `<algorithm_name>_service.py` files to appropriate suggestion folder.

- I added `__init__.py` file to each suggestion folder, since we import them in `cmd/`.

- I made absolute path in all python files. For example: https://github.com/kubeflow/katib/compare/master...andreyvelich:issue-1144-suggestion-folder-structure?expand=1#diff-fe0ee80956c02a4ffe8ecf4881b2e40cR6. To be consistent between imports.

- I moved `base_health_service` to `internal` folder.

- I deleted `pkg/suggestion/test_requirements.txt ` file. @gaocegege Do we need this file? I didn't find any usage of this file.

### CODE REVIEW

**Comment by andreyvelich** [comment]
> Thank you for your work!
> 
> It might be better to rename files like:
> 
> * `suggestion/chocolate/chocolate_service.py` -> `suggestion/chocolate/service.py`
> * `suggestion/hyperband/hyperbad_service.py` -> `suggestion/hyperbad/service.py`
> * `suggestion/skopt/skopt_service.py` -> `suggestion/skopt/service.py`
> * ...
> 
> But I have no strong opinion about this. And we can work on it in another pull request.
> 
> /lgtm

Good point. I will rename it. 
What do you think about Base Services: https://github.com/andreyvelich/katib/blob/issue-1144-suggestion-folder-structure/pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py ?
Maybe name it `base_service.py` ?

**Comment by c-bata** [comment]
> Maybe name it base_service.py ?

Yeah, agree.

**Pull request merged**
