### PR TITLE
Update Changelog for Katib 0.12.0-rc.0 release

### PR DESCRIPTION
**Pull request by andreyvelich**
I updated Changelog for Katib 0.12.0-rc.0 release.

I combined our work in these sections:
```
New Features
  Algorithms and Components
  UI Features
Documentation
Bug Fixes
Misc
```

@gaocegege @johnugeorge @jbottum Please let me know what do you think about it ?

cc @c-bata @g-votte @anencore94 @RFMVasconcelos @knkski 

/hold for the review

### CODE REVIEW

**Comment by anencore94** [comment]
/lgtm
Looks thoughtful! @andreyvelich
Maybe later, not this release, we could work on automating grouping PRs by labeling on each pr when pr created from [this script](https://github.com/kubeflow/katib/blob/21580f66972640ee60aea0f86d74a4f496ee98c3/docs/release/changelog.py)

**Comment by johnugeorge** [comment]
Grid changes is in the next release cut?

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Comment by andreyvelich** [comment]
> Grid changes is in the next release cut?

Yes, it will be in Katib 0.12.0-rc.1 release or in Katib 0.12.0 release.

Thanks everyone for the review!
/hold cancel

**Pull request merged**
