### PR TITLE
Fix: Empty Trial templates in Katib UI

### PR DESCRIPTION
**Pull request by andreyvelich**
In this PR:
1. Fixed empty page while clicking on Trial Manifests in the Menu
2. Fetch Trial templates when opening submit by parameters in NAS page.

I did it in v1alpha3 version, should I make changes in v1alpha2 also @johnugeorge @gaocegege ?

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/938)

### CODE REVIEW

**Comment by gaocegege** [comment]
Welcome back!

/retest

I do not think we need to update v1alpha2.

/lgtm

**Comment by johnugeorge** [comment]
@andreyvelich i see that UI build fails randomly. Can you take a look at it?

**Comment by andreyvelich** [comment]
> Welcome back!
> 
> /retest
> 
> I do not think we need to update v1alpha2.
> 
> /lgtm

Hi, thank you! :)

**Comment by johnugeorge** [comment]
what is the reason for sudden flakiness in CI?

**Comment by andreyvelich** [comment]
@johnugeorge I think it fails on this example https://github.com/kubeflow/katib/blob/master/examples/v1alpha3/file-metricscollector-example.yaml in e2e test

**Pull request merged**
