### PR TITLE
Dedicated yaml tab for Trials

### PR DESCRIPTION
**Pull request by elenzio9**
This PR introduces a new yaml tab in the Trial details page that shows the full YAML as it comes from the backend. 

Here's a screenshot:
image

Related issue: https://github.com/kubeflow/katib/issues/2011

### CODE REVIEW

**Comment by johnugeorge** [comment]
Great work @elenzio9

**Comment by johnugeorge** [comment]
Related Issue for Suggestion: https://github.com/kubeflow/katib/issues/1439

**Comment by kimwnasptd** [comment]
@orfeas-k since you've also helped with developing the monaco editor component https://github.com/kubeflow/kubeflow/pull/6733 could you also take a stab at the review?

/cc @kimwnasptd 
/cc @orfeas-k

**Comment by orfeas-k** [comment]
Just a small nit @elenzio9 you could rename [openTrialModal() ](https://github.com/kubeflow/katib/blob/d9b4602280748e2fb322bffef95d02dda92664cb/pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.html#L26) as well. Everything else lgtm @kimwnasptd

**Review by orfeas-k — COMMENTED** [review]
Just a small nit @elenzio9 you could rename [openTrialModal() ](https://github.com/kubeflow/katib/blob/d9b4602280748e2fb322bffef95d02dda92664cb/pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.html#L26)as well. Everything else lgtm @kimwnasptd

**Pull request merged**
