### PR TITLE
Add NAS team as reviewers

### PR DESCRIPTION
**Pull request by andreyvelich**
I updated reviewers in OWNERS.
/assign @YujiOshima

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/419)

### CODE REVIEW

**Comment by YujiOshima** [comment]
@andreyvelich Thanks! LGTM.
/cc @richardsliu @johnugeorge @hougangliu @gaocegege

**Comment by hougangliu** [comment]
/lgtm
Thanks

**Pull request merged**
