### PR TITLE
[Adopters] change adopter of Ant Group

### PR DESCRIPTION
**Pull request by sperlingxx**
Hi @andreyvelich @gaocegege @johnugeorge @hougangliu  , 

For some reasons, I will no longer work as katib adopter for Ant Group in soon time. And I recommend @ohmystack to take over this position, who is the architect and primary contributor of our internal platform.

I am very pleased that I had chance to collaborate with katib community. And I really appreciate for suggestions and code reviews from community, which helps me a lot.

### CODE REVIEW

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Comment by andreyvelich** [comment]
Thank you @sperlingxx for doing amazing contributions!
Can you make new empty commit to trigger CI and re-run test, please?

**Comment by sperlingxx** [comment]
> Thank you @sperlingxx for doing amazing contributions!
> Can you make new empty commit to trigger CI and re-run test, please?

This PR was closed accidentially.  I have reapplied it at #1327 .

**Pull request closed without merging**
