### PR TITLE
Unit test for resuming Experiment in controller reconcilers

### PR DESCRIPTION
**Pull request by andreyvelich**
I updated unit test for Experiment and Suggestion controllers.
I tried to make `suite_test` consistent between these controllers and cover more reconciler source code for resume Experiment feature.
For Experiment controller, I deleted `TestCreateExperiment`, because it doesn't add any additional tests with `TestReconcile`. 
Instead of that, I added `TestCompleteExperiment`.

Later, I will update Trial controller `suite_test` also.

/assign @johnugeorge @gaocegege

### CODE REVIEW

**Comment by andreyvelich** [comment]
@sperlingxx I deleted `buildTrialMetaForRunSpec` function from Experiment controller, I suppose in the new design you don't use it.

**Comment by gaocegege** [comment]
Please fix the CI errors.

**Comment by gaocegege** [comment]
Retest does not work for Travis. Please try to force push and trigger a new build.

**Comment by sperlingxx** [comment]
> buildTrialMetaForRunSpec

Yes, it is useless.

**Comment by andreyvelich** [comment]
@gaocegege I can see that test are passed.

**Comment by andreyvelich** [comment]
I refactored Experiment test to make it more stable and it should be succeeded even if Controller fails [here](https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/experiment/experiment_controller.go#L252-L257).
Now in `TestReconcile` I have added full workflow of Experiment. Created->Running->Succeeded->Restarting which makes more sense.

Do we actually need to traceback error [here](https://github.com/kubeflow/katib/blob/master/pkg/controller.v1beta1/experiment/experiment_controller.go#L252), if `updateStatusHandler` failed. 
Maybe we could give `logger.Info` there and `return reconcile.Result{}, nil`, since controller will reconcile Experiment after this error?
That can improve Controller logging.
What do you think @gaocegege @johnugeorge @sperlingxx ?

**Comment by gaocegege** [comment]
If we do not retry, how to deal with temporary failures?

**Comment by andreyvelich** [comment]
@gaocegege As I can see, this error can happen because resource version was modified for Experiment object, and it is more like Warning message (see comment: https://github.com/kubernetes/kubernetes/issues/28149#issuecomment-229469157).

If update status was unsuccessful, maybe we can `Get` Experiment object again and try to update it, instead of traceback this error and run whole reconcile loop again?

**Comment by gaocegege** [comment]
I think resource version problems will be resolved in the next reconcile loop. Then we will just have one warning here instead of always reconciling it.

**Comment by andreyvelich** [comment]
> I think resource version problems will be resolved in the next reconcile loop. Then we will just have one warning here instead of always reconciling it.

Currently, we print error message instead of warning. Do you think it makes sense to print error in case of not sync objects version?

**Comment by gaocegege** [comment]
Can we requeue the request but not raise an error like this?

```
return reconcile.Result{
			Requeue: true,
		}, nil
```

**Comment by andreyvelich** [comment]
> Can we requeue the request but not raise an error like this?
> 
> ```
> return reconcile.Result{
> 			Requeue: true,
> 		}, nil
> ```

Sure! Will make this change in the follow PR

**Pull request merged**
