### PR TITLE
katib manager db error

### PR DESCRIPTION
**Pull request by hougangliu**
`condition` is keyword of mysql, we need escape it in sql, otherwise an error in your SQL syntax occurs

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/476)

### CODE REVIEW

**Comment by johnugeorge** [comment]
instead of this, is it better to rename thee field? may be `status`?  WDYT?

**Comment by YujiOshima** [comment]
I agree with @johnugeorge.

**Comment by hougangliu** [comment]
@YujiOshima @johnugeorge agree with you, I will update it to `status`

**Pull request merged**
