### PR TITLE
Replace gRPC code generation tool from Znly/protoc to Buf

### PR DESCRIPTION
**Pull request by shivas1516**
**What this PR does / why we need it**:
This PR replaces the outdated code generation tool 'znly/protoc' with Buf for generating gRPC code. The change is necessary due to the lack of maintenance and updates for 'znly/protoc', ensuring compatibility, security, and access to new features with Buf.

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes: #2141

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by shivas1516** [comment]
@tenzen-y I reached out to the Buf community and received valuable suggestions on migrating our project from znly/protoc to Buf. Following their guidance, I successfully set up Buf and generated the code. However, during testing, some test cases are failing. I've been reviewing them for more than two days now. Any suggestions on resolving these failures would be greatly appreciated as it would help me to solve them. Thank you!

**Review by andreyvelich — COMMENTED** [review]
Sorry for the late reply @shivas1516 and thank you for your contribution!
I think, we should update [our generate scripts](https://github.com/kubeflow/katib/blob/master/pkg/apis/manager/v1beta1/build.sh) to include this new way of gRPC code generation in our CI/CD.

**Comment by shivas1516** [comment]
> Sorry for the late reply @shivas1516 and thank you for your contribution!
> I think, we should update [our generate scripts](https://github.com/kubeflow/katib/blob/master/pkg/apis/manager/v1beta1/build.sh) to include this new way of gRPC code generation in our CI/CD.

Sir @andreyvelich , If you think I can do this task(as mentioned this is a good first issue), Please give any suggestions or guidance. So that, I can try my level best to complete this and make a meaningful contribute to Kuberflow.

**Comment by andreyvelich** [comment]
> > Sorry for the late reply @shivas1516 and thank you for your contribution!
> > I think, we should update [our generate scripts](https://github.com/kubeflow/katib/blob/master/pkg/apis/manager/v1beta1/build.sh) to include this new way of gRPC code generation in our CI/CD.
> 
> Sir @andreyvelich , If you think I can do this task(as mentioned this is a good first issue), Please give any suggestions or guidance. So that, I can try my level best to complete this and make a meaningful contribute to Kuberflow.

Did you generate all files using the following command:
```
buf generate --template=buf.gen.yaml $proto
```
We might need to add this CLI as a requirements to our docs: https://github.com/kubeflow/katib/blob/master/docs/developer-guide.md#requirements

**Review by andreyvelich — COMMENTED** [review]
@shivas1516 Please can you collaborate with @forsaken628 to update this PR with required changes from this PR: https://github.com/kubeflow/katib/pull/2344.

For example, we need to have hack script to update protobuf: https://github.com/kubeflow/katib/pull/2344/files#diff-a2e208c47cfc7e9e58c84651f3eb55489fb00b7303c249eab47775a8f52d7ba2

Feel free to use #kubeflow-katib Slack channel to discuss what we need to add in this PR to get it merged.

**Comment by andreyvelich** [comment]
As we discussed on #kubeflow-training Slack, we will work on this PR: https://github.com/kubeflow/katib/pull/2344 to update buf.

**Pull request closed without merging**
