### PR TITLE
Documentation for the Katib Config

### PR DESCRIPTION
**Pull request by andreyvelich**
I added documentation about Katib config. 

Please, check if everything is fine.

/assign @johnugeorge @gaocegege 

/cc @richardsliu @sarahmaddox

### CODE REVIEW

**Comment by sarahmaddox** [comment]
@andreyvelich thanks for this doc! I think it would be best to merge the info into the existing docs on kubeflow.org, rather than putting the doc into the katib repo. Our goal is to have all docs for Kubeflow users on kubeflow.org, and docs for Kubeflow contributors in the individual repos.

These are the existing user docs for Katib:
https://www.kubeflow.org/docs/components/hyperparameter-tuning/

The docs are in the `kubeflow/website` repo:
https://github.com/kubeflow/website/tree/master/content/docs/components/hyperparameter-tuning

The basic workflow for updating the docs is the same as for updating any other code file. Full instructions are here, including how to see a preview of your updates:
https://github.com/kubeflow/website/blob/master/README.md

**Comment by andreyvelich** [comment]
@sarahmaddox Sure, will add it.

**Comment by andreyvelich** [comment]
/close
Close this, I created PR in the website: https://github.com/kubeflow/website/pull/1839.

**Pull request closed without merging**
