### PR TITLE
make job name contain the name of studyName

### PR DESCRIPTION
**Pull request by wukong1992**
#195 @YujiOshima

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/196)

### CODE REVIEW

**Comment by jlewi** [comment]
@wukong1992 Its looks like you already opened a PR; #187 to fix this?

**Comment by wukong1992** [comment]
@jlewi Yes, I changed my own branch, how can I solve this？

**Comment by wukong1992** [comment]
@YujiOshima I didn't know where it is wrong.

**Comment by YujiOshima** [comment]
```
# github.com/kubeflow/katib/pkg/db
../../pkg/db/interface.go:689:3: undefined: row
../../pkg/db/interface.go:691:8: undefined: row
../../pkg/db/interface.go:693:8: undefined: row
../../pkg/db/interface.go:694:28: undefined: row
../../pkg/db/interface.go:696:9: undefined: row
../../pkg/db/interface.go:696:19: undefined: worker_id
../../pkg/db/interface.go:698:4: cannot use nil as type string in return argument
../../pkg/db/interface.go:700:23: cannot convert '-' (type untyped number) to type string
../../pkg/db/interface.go:700:23: invalid operation: workerID + '-' (mismatched types string and rune)
../../pkg/db/interface.go:700:31: undefined: generate_randid
../../pkg/db/interface.go:700:31: too many errors
The command '/bin/sh -c go build -o vizier-manager' returned a non-zero code: 2
ERROR
```

This is the error messages. Please fix them.

**Comment by wukong1992** [comment]
> ```
> # github.com/kubeflow/katib/pkg/db
> ../../pkg/db/interface.go:689:3: undefined: row
> ../../pkg/db/interface.go:691:8: undefined: row
> ../../pkg/db/interface.go:693:8: undefined: row
> ../../pkg/db/interface.go:694:28: undefined: row
> ../../pkg/db/interface.go:696:9: undefined: row
> ../../pkg/db/interface.go:696:19: undefined: worker_id
> ../../pkg/db/interface.go:698:4: cannot use nil as type string in return argument
> ../../pkg/db/interface.go:700:23: cannot convert '-' (type untyped number) to type string
> ../../pkg/db/interface.go:700:23: invalid operation: workerID + '-' (mismatched types string and rune)
> ../../pkg/db/interface.go:700:31: undefined: generate_randid
> ../../pkg/db/interface.go:700:31: too many errors
> The command '/bin/sh -c go build -o vizier-manager' returned a non-zero code: 2
> ERROR
> ```
> This is the error messages. Please fix them.

how to see error messages when test failed.

**Comment by YujiOshima** [comment]
@wbuchwalter Please access to `link` of k8s-ci-robot comment.
You can find the result of test for your PR  at `http://testing-argo.kubeflow.org/workflows/kubeflow-test-infra/~` .

**Comment by YujiOshima** [comment]
@wukong1992 I'm confusing what you need.
Which name do you add to worker StudyName or StudyJobName?
These are different since Study and StudyJob is different.
StudyJob is a CR of k8s and it is not a persistent resource. 
The StudyJob will make Study. And the Study will be stored in DB.

In your PR, you use StudyName but the PR title is `contain the name of studyjob`

**Comment by wukong1992** [comment]
> @wukong1992 I'm confusing what you need.
> Which name do you add to worker StudyName or StudyJobName?
> These are different since Study and StudyJob is different.
> StudyJob is a CR of k8s and it is not a persistent resource.
> The StudyJob will make Study. And the Study will be stored in DB.
> 
> In your PR, you use StudyName but the PR title is `contain the name of studyjob`

sorry, should use 'contain the name of studyNmae'

**Comment by YujiOshima** [comment]
@wukong1992 Why not adding `study_name` field to Worker and Trial instead of including it to their id?
You can easy to get Worker and Trial by a StudyName from DB.

**Comment by YujiOshima** [comment]
@wukong1992 What do you think about my comment?
>adding study_name field to Worker and Trial instead of including it to their id

I think it would be good since we will be able to get any resources by `studyname`.
It would be also helpful for the UI. I want to summarize results not only studyID but studyName on UI.

**Comment by gaocegege** [comment]
/close

Now are have dropped v1alpha1. Thus I think we cannot merge it into master.

Thanks for the PR.

**Pull request closed without merging**
