### PR TITLE
Fix broken client-example.go

### PR DESCRIPTION
**Pull request by vinaykakade**
With the recent changes in the repo (https://github.com/kubeflow/katib/pull/110), I found that client-example.go no longer works. There are two issues:
(1) With having 'matrics\n - accuracy' in study-config, the CreateStudy request no longer is successful. Until the underlying cause is found/fixed, removing it from study-config. Let me know in case replacing it with something else works.
(2) Even after the workers terminate successfully, the client-example.go is no longer able to detect their termination and keeps on running in an infinite loop. Reverted to the original terminal condition change which works correctly.

/assign @YujiOshima

### CODE REVIEW

**Comment by YujiOshima** [comment]
I have no error on client-example.go.
Maybe there is some mismatch between client and server.
Which docker image do you use for vizier-core?

**Comment by lluunn** [comment]
I was also able to run client-example.go (last week)

**Comment by vinaykakade** [comment]
Thanks, I'll check for the mismatch between client and server.

**Comment by jlewi** [comment]
@vinaykakade Were you successful?

**Comment by vinaykakade** [comment]
Yes, was able to run it long ago. Apologies for not reporting this sooner. Will close this PR.

**Comment by wukong1992** [comment]
@vinaykakade How did you solve it?

**Comment by vinaykakade** [comment]
The issue was mismatched images in dockerhub and the tip of master. I had to rebuild the images, upload them to an image repository we use, and point the manifest for vizier-core to pull the image from our repository instead of dockerhub.

**Pull request closed without merging**
