### PR TITLE
Replace kubeflow-images-staging with kubeflow-images-public

### PR DESCRIPTION
**Pull request by ankushagarwal**
Related to https://github.com/kubeflow/kubeflow/issues/534

/cc YujiOshima
/cc gaocegege

### CODE REVIEW

**Comment by YujiOshima** [comment]
/lgtm
Thanks!

**Comment by YujiOshima** [comment]
@gaocegege CI doesn't work now?

**Comment by gaocegege** [comment]
Yeah, we renamed the repo and the code in k8s test infra should be changed. I will merge it manually

**Pull request merged**
