### PR TITLE
Change tell method for BO Suggestion

### PR DESCRIPTION
**Pull request by andreyvelich**
Fixes: https://github.com/kubeflow/katib/issues/1052.

/assign @gaocegege @johnugeorge 
/cc @richardsliu @hougangliu

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/1055)

### CODE REVIEW

**Comment by johnugeorge** [comment]
Can you add PR description

**Comment by andreyvelich** [comment]
> Can you add PR description

After this PR `skopt_suggested` will contains information of all Trials assignments and `loss_for_skopt` will be list of all Trials observation value. We will run `tell` method once with all Trials information instead of running it for every trial.

**Pull request merged**
