### PR TITLE
feat(experiment_status): Add trial name

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <gaoce@caicloud.io>

**What this PR does / why we need it**:

This PR added a new field in v1alpha3 Exepriment status, which stores the best trial name.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/986)

### CODE REVIEW

**Comment by hougangliu** [comment]
/lgtm
BTW, for `observation` field, now we only show objective metric and  "best" value. in fact, we can add "min", "max", "latest" value for more information like other platform (such as ray), WDYT?

**Comment by gaocegege** [comment]
We show metrics and parameter assignments. I am not sure if I get your idea. Could you please explain more?

**Comment by hougangliu** [comment]
> We show metrics and parameter assignments. I am not sure if I get your idea. Could you please explain more?

for example, for now if objective metrics is `loss`, in experiment or trial status, it show the best `loss` metrics minimum value like below:
```
observation:
  metrics:
    - name: loss
       value: 0.0001
```

we can detail it more for a better viewpoint like `ray`:
 ```
observation:
  metrics:
    - name: loss
      min: 0.0001
      max: 0.1234
      latest: 0.1111
```

**Comment by gaocegege** [comment]
Gotcha. SGTM

**Comment by hougangliu** [comment]
> Gotcha. SGTM

/approve
We can enhance it in other PR

**Pull request merged**
