### PR TITLE
[hotfix]: filter by name of experiment

### LINKED ISSUE #1919: list_trials function do not respect experiment name filter
/kind bug

**What steps did you take and what happened:**

`KatibClient.list_trials` function is broken, it no more respects to the experiment name parameter, it returns all the existing trials for all the experiments.  As you'll see `name` parameter is only used in the Exception message now.

**What did you expect to happen:**

I expect it to return the filtered trails of the experiment whose name is passed as a parameter.

**Anything else you would like to add:**
It's broken in this [PR](https://github.com/kubeflow/katib/pull/1630/files#diff-bc6841536c6ef19d4354a2de49e5f29e9863be2d42a70b774c048eb6371bb14cL343-R347).

**Environment:**

- Katib version (check the Katib controller image version): v0.13.0
- Kubernetes version: (`kubectl version`): v1.20.15
- OS (`uname -a`): `Linux ... 5.4.188-104.359.amzn2.x86_64 #1 SMP Thu Apr 14 20:53:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

### PR DESCRIPTION
**Pull request by anencore94**
Signed-off-by: Jaeyeon Kim <anencore94@gmail.com>

**What this PR does / why we need it**:
- To fix sdk's bug which is unavailable to list trials filter by experiment's name.
  - It was broken not from #1630. The condition was broken from the first time at #1177. It didn't cover the case when `name` was not given.

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #1919

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Review by gaocegege — APPROVED** [review]
/lgtm

**Comment by anencore94** [comment]
I guess there was some network issue for failed e2e test. How to re-run such github action workflow ? @gaocegege

**Comment by gaocegege** [comment]
I rerun the test manually.

There is no way to trigger github action with the bot, I think.

**Pull request merged**
