### PR TITLE
improve frontend

### PR DESCRIPTION
**Pull request by YujiOshima**
Fix bug and little improve for UI
bugs
* Categorical parameter didn't be select range by drag at the parallel coordinate graph.
* Fail to link TensorBoard.

improves
* Get an overview of the models selected by the parallel coordinate graph.
* Improve visualization of the parallel coordinate graph.

ss

Signed-off-by: YujiOshima <yuji.oshima0x3fd@gmail.com>

### CODE REVIEW

**Comment by gaocegege** [comment]
I think I have no ability to review frontend code now, thus let us go ahead and invite some people has frontend background to be reviewers.

/lgtm

**Comment by gaocegege** [comment]
/hold

Does it WIP or done?

**Comment by YujiOshima** [comment]
@gaocegege Thanks. I agree we need frontend reviewer.
This is done. We can marge it.

**Pull request merged**
