### PR TITLE
[new-ui] Bump angular version to 12

### LINKED ISSUE #1590: [ui] Bump Angular version to 12
/kind feature

**Describe the solution you'd like**
The other web apps in kubeflow/kubeflow have moved to Angular 12 kubeflow/kubeflow#5525. We should also update this UI which is using Angular 8. This is required to also use the latest common frontend code from `kubeflow/kubeflow`.

**Anything else you would like to add:**
The work for this will need to start after kubeflow/kubeflow#6065 is merged which refactors the common code. Without that PR the Katib UI would need to be integrated with `ngx-translate` which is something we want to avoid kubeflow/kubeflow#6042

After I make this update I'll be able to start working on the next more advanced features like #1440

### PR DESCRIPTION
**Pull request by seong7**
**What this PR does / why we need it**:
Updates Angular version from 8 to 12 (latest).
Details are described in the issue #1590 

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #1590

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by seong7** [comment]
@andreyvelich @kimwnasptd 
Can anyone help me with this `kubeflow-katib-presubmit` test failure?
I cannot figure out what is wrong.

**Comment by andreyvelich** [comment]
> @andreyvelich @kimwnasptd Can anyone help me with this `kubeflow-katib-presubmit` test failure? I cannot figure out what is wrong.

I can see the follow error in the UI build:
```
     Compiling @angular/material/chips : es2015 as esm2015
Compiling @fortawesome/angular-fontawesome : es2015 as esm2015
An error occurred during the build:
Error: The target entry-point "kubeflow" has missing dependencies:
 - @angular/cdk-experimental/clipboard
    at TargetedEntryPointFinder.findEntryPoints (/src/node_modules/@angular/compiler-cli/ngcc/src/entry_point_finder/targeted_entry_point_finder.js:40:23)
    at /src/node_modules/@angular/compiler-cli/ngcc/src/execution/analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (/src/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:28:29)
    at /src/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:59
    at SyncLocker.lock (/src/node_modules/@angular/compiler-cli/ngcc/src/locking/sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (/src/node_modules/@angular/compiler-cli/ngcc/src/execution/single_process_executor.js:57:27)
    at Object.mainNgcc (/src/node_modules/@angular/compiler-cli/ngcc/src/main.js:74:25)
    at Object.process (/src/node_modules/@angular/compiler-cli/ngcc/index.js:29:23)
    at NgccProcessor.processModule (/src/node_modules/@ngtools/webpack/src/ngcc_processor.js:175:16)
    at /src/node_modules/@ngtools/webpack/src/ivy/host.js:146:18
An unhandled exception occurred: The target entry-point "kubeflow" has missing dependencies:
 - @angular/cdk-experimental/clipboard
See "/tmp/ng-QLHZMq/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! frontend@0.0.0 build:prod: `npm run copyLibAssets && ng build --base-href /katib/ --deploy-url /katib/static/  --outputPath dist/static --configuration prod
uction`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the frontend@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-01T07_02_35_205Z-debug.log
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

You can check it here: https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-katib-presubmit-e2e-v1beta1-1712-82b1f2e-3872-f3a5?tab=workflow&nodeId=kubeflow-katib-presubmit-e2e-v1beta1-1712-82b1f2e-3872-f3a5-4236534848&sidePanel=logs%3Akubeflow-katib-presubmit-e2e-v1beta1-1712-82b1f2e-3872-f3a5-4236534848%3Amain.

@seong7 Were you able to build the UI image locally ?

**Comment by seong7** [comment]
> You can check it here: https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-katib-presubmit-e2e-v1beta1-1712-82b1f2e-3872-f3a5?tab=workflow&nodeId=kubeflow-katib-presubmit-e2e-v1beta1-1712-82b1f2e-3872-f3a5-4236534848&sidePanel=logs%3Akubeflow-katib-presubmit-e2e-v1beta1-1712-82b1f2e-3872-f3a5-4236534848%3Amain.
> 
> @seong7 Were you able to build the UI image locally ?

@andreyvelich Thanks! I managed to find what went wrong from the error log you gave.
Now it's all set to be reviewed!

**Comment by seong7** [comment]
Can we know the progress of this PR? 😄

**Comment by kimwnasptd** [comment]
@seong7 apologies, I was the blocker here. I'm running very low on cycles in the past couple of weeks.

I'll get to it either later today or tomorrow.

**Comment by kimwnasptd** [comment]
@seong7 the commits and changes LGTM, very nice work!

My only concern is with sticking to [`ng2-ace-editor`](https://github.com/fxmontigny/ng2-ace-editor). I see people are having issues with it and Angular 12:
* https://github.com/fxmontigny/ng2-ace-editor/issues/118
* https://github.com/fxmontigny/ng2-ace-editor/issues/141

I would suggest we that we should instead use the [`monaco-editor`](https://github.com/microsoft/monaco-editor) that is developed by Microsoft (MIT).

But I don't want to block your work for this, since we can do this later on. I'll create an issue to track this though since it might become a problem in the future.

Again thank you for the stellar work!
/lgtm
/approve

**Comment by kimwnasptd** [comment]
The PR also touched the README and Dockerfile, for which I don't have permissions to approve.

@andreyvelich from my part this is good to go. I also tested it locally and with the produced Docker image. If you don't have any further suggestions I believe we can merge this.

**Comment by kimwnasptd** [comment]
Actually 
/hold

I see that the the `package-lock.json` is using the `"lockfileVersion": 2`, which means npm 7 was used. There's also some discussion with this in https://github.com/kubeflow/katib/pull/1704#discussion_r725403446. Looking into understanding if we are OK with migrating to npm 7.

We will also need to update the:
1. Dockerfile to use node 15, which comes with npm 7
2. README to update the node and npm version someone should use locally

If we move to npm 7. I'll provide some more input

**Comment by kimwnasptd** [comment]
So after looking more into it I propose to either stick with `node v12` and `npm 6`, or maybe use `node v14` and `npm 6` which is also what is used from the other KF web apps and Pipelines. But not jump to `node v16` and `npm 8` yet.

I tried to build the common library with `node v16` and `npm 8` and bumped into a lot of warning logs like these:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics@12.0.5',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular/cli@12.0.5',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || >=14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.13.0', npm: '8.1.0' }
npm WARN EBADENGINE }
```

The requirements express that these packages can work with `node v16`, but not with `npm 8.10` that comes along that version of node https://nodejs.org/en/download/. There's also an upstream comment that mentions Angular 12 is not yet fully ready for `node v16` https://github.com/angular/angular-cli/issues/20757#issuecomment-840485441. Lets also not jump to `node v15` and only stick to LTS versions https://nodejs.org/en/about/releases/.

**Comment by kimwnasptd** [comment]
@seong7 could you instead use either `node v12` or `node v14` and update the `package-lock.json`? Doing an `npm i` should do the trick, after you used on of the above versions.

I'm OK with going with `node v14` as well, but in that case please add a commit to:
1. Update the README of the frontend to mention the new version of Node, and lets also mention the npm version https://github.com/kubeflow/katib/blob/master/pkg/new-ui/v1beta1/README.md#requirements
2. Update the dockerfile of the web app to use that version of node in https://github.com/kubeflow/katib/blob/master/cmd/new-ui/v1beta1/Dockerfile#L12 and in https://github.com/kubeflow/katib/blob/master/cmd/new-ui/v1beta1/Dockerfile#L24

**Comment by andreyvelich** [comment]
Thank you for the review @kimwnasptd.
@seong7 What do you think about this PR ? Are we going to finish it before Kubeflow 1.5 release ?

**Comment by seong7** [comment]
@kimwnasptd 
Since this PR is entitled to bump Angular version not Node and npm, I think we better stick with node v12 and npm 6.
For Node and npm, we will need separated issue to work only if we need.
Thank you so much for dive deep deep down on this issue.

I will push a commit that rollbacks the version of lock file to v1.
Is there anything else I should do for it?

@andreyvelich 
When is the due date to finish the PR to get it included in Kubeflow 1.5?

**Comment by kimwnasptd** [comment]
> Since this PR is entitled to bump Angular version not Node and npm, I think we better stick with node v12 and npm 6.
For Node and npm, we will need separated issue to work only if we need.

I completely agree!

> I will push a commit that rollbacks the version of lock file to v1.
> Probably we should update the README as below to specify the versions? WTYT?
https://github.com/kubeflow/katib/tree/master/pkg/new-ui/v1beta1#requirements

Perfect, these two would be awesome! We should be good to merge afterwards.

> @andreyvelich
When is the due date to finish the PR to get it included in Kubeflow 1.5?

The currently proposed date is Jan 13 https://github.com/kubeflow/community/pull/538 for the beginning of Feature Freeze. At that date the WGs should have a pass and pick which PRs, under review, should be merged for the next two weeks and also be very very conservative with adding new features.

But we are almost ready for merging this, so I don't think we'll have an issue with this PR

**Comment by seong7** [comment]
@kimwnasptd 
Sorry for the delay.
I think this PR is ready to be merged now.
Please take a look into the 2 commits.

Thank you !

**Comment by kimwnasptd** [comment]
All tests have passed, so we should be good to go. Thank you so much for your effort @seong7, this was great work!

/lgtm
/approve

**Comment by kimwnasptd** [comment]
@andreyvelich this will also need an `/approve` from you as well, since it touches the README of the app

**Comment by seong7** [comment]
@andreyvelich Can we proceed this PR before January 15th?

**Comment by andreyvelich** [comment]
> @andreyvelich Can we proceed this PR before January 15th?

Sorry for the long reply @seong7.
I need some time to review the new changes.

I am on holidays until end of this week, and I will take a look at this PR on the next week.

**Comment by seong7** [comment]
Thank you for replying @andreyvelich .
No problem.

**Comment by andreyvelich** [comment]
Overall, this PR looks good.
@seong7 Do we need to keep all these fonts under `/assets/fonts` ?

**Comment by seong7** [comment]
> Overall, this PR looks good. @seong7 Do we need to keep all these fonts under `/assets/fonts` ?

I don't think we need those font files, but it keeps being generated automatically on `npm i`.
I've done some research, but I can't figure out what makes these font files being generated.

**Comment by andreyvelich** [comment]
@seong7 As we discussed on the community meeting with @kimwnasptd we can add the `font` folder under `.gitignone`.
It is not necessary to have these files under Katib repository.

**Comment by seong7** [comment]
> @seong7 As we discussed on the community meeting with @kimwnasptd we can add the `font` folder under `.gitignone`.
> It is not necessary to have these files under Katib repository.

@andreyvelich Thank you for the quick decision. Please have look into the new commit.

**Comment by andreyvelich** [comment]
Thank you for the update @seong7!
Feel free to unhold this PR.
/lgtm
/approve
/cc @kimwnasptd

**Pull request merged**
