### PR TITLE
Fix problem with Hyperopt Out of Range error

### PR DESCRIPTION
**Pull request by andreyvelich**
See comment: https://github.com/kubeflow/katib/issues/1314#issuecomment-681076525.
After this fix, we should not see `list index out of range` error.

/assign @gaocegege @sperlingxx 
/cc @jimmy-hawkfish

### CODE REVIEW

**Review by sperlingxx — APPROVED** [review]
/lgtm

**Review by gaocegege — COMMENTED** [review]
/lgtm

**Pull request merged**
