### PR TITLE
add resources to earlystopping container

### LINKED ISSUE #2037: Set earlyStopping container resource requests/limits
/kind feature

Describe the solution you'd like:

When submitting a katib experiment, earlyStoppingContainer Container resources should be set.

### PR DESCRIPTION
**Pull request by zhixian82**
Fixes #2037

### CODE REVIEW

**Review by andreyvelich — COMMENTED** [review]
Thank you for this update @zhixian82!
Please can you update [the unit test](https://github.com/kubeflow/katib/blob/ad6b4b1aa8ea53e7aa5dc6ba26f19a017f2d8bd2/pkg/util/v1beta1/katibconfig/config_test.go#L172) with Early Stopping container resources ?

**Comment by zhixian82** [comment]
> Thank you for this update @zhixian82! Please can you update [the unit test](https://github.com/kubeflow/katib/blob/ad6b4b1aa8ea53e7aa5dc6ba26f19a017f2d8bd2/pkg/util/v1beta1/katibconfig/config_test.go#L172) with Early Stopping container resources ?

Done

**Comment by andreyvelich** [comment]
Thanks @zhixian82!
/lgtm
/assign @tenzen-y @johnugeorge

**Comment by johnugeorge** [comment]
Thanks @zhixian82 

/approve

**Pull request merged**
