### PR TITLE
fix katib use crds token pipeline trail template guide

### PR DESCRIPTION
**Pull request by Jerry-yz**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Fixes #

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

### CODE REVIEW

**Comment by Jerry-yz** [comment]
> **What this PR does / why we need it**:
> fix document update [Use CRDs with Trial Template ](https://www.kubeflow.org/docs/components/katib/user-guides/trial-template/#use-crds-with-trial-template), but sync here [Katib Examples with Tekton Pipelines Integration](https://github.com/kubeflow/katib/tree/master/examples/v1beta1/tekton)
> **Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_: Fixes #
>  fix issue #2327 
> **Checklist:**
> 
> * [ ]  [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

**Review by andreyvelich — COMMENTED** [review]
Thank you for this update @Jerry-yz!
I noticed that we have appropriate steps to support Tekton pipeline with Katib Trial here: https://www.kubeflow.org/docs/components/katib/user-guides/trial-template/#use-crds-with-trial-template
Should we just link this guide to the Katib controller section ?

**Comment by Jerry-yz** [comment]
> Thank you for this update @Jerry-yz! I noticed that we have appropriate steps to support Tekton pipeline with Katib Trial here: https://www.kubeflow.org/docs/components/katib/user-guides/trial-template/#use-crds-with-trial-template Should we just link this guide to the Katib controller section in this doc?

i have update it, you can review it, thanks?

**Comment by andreyvelich** [comment]
Thank you for your contribution @Jerry-yz!
/lgtm
/approve

**Comment by andreyvelich** [comment]
@Jerry-yz Please rebase your PR to fix the CI/CD.

**Review by tenzen-y — COMMENTED** [review]
Thank you!
/lgtm

**Pull request merged**
