### PR TITLE
feat: Add liveness probe for DB

### PR DESCRIPTION
**Pull request by gaocegege**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubeflow/katib/issues/334

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/871)

### CODE REVIEW

**Comment by gaocegege** [comment]
/assign @johnugeorge 

Not sure if we should merge it before 0.7

It requires some change to kf/manifests, I think.

**Comment by johnugeorge** [comment]
This would help users right?. In that case, shall we add to kf/manifests too?

**Comment by gaocegege** [comment]
It will be helpful. But there may be a blocker that we cannot upgrade from 8.0.3 to 8(8.0.17) painlessly. I need to delete /tmp/katib to clean the directory first.

**Comment by gaocegege** [comment]
But I think it works for us since it solves #334

**Comment by johnugeorge** [comment]
@gaocegege are you talking backward compatibility ? It is not compatible now anyways

**Comment by gaocegege** [comment]
@johnugeorge Yeah, then I think we can merge it into kf/manifests.

**Comment by johnugeorge** [comment]
I will wait for @hougangliu

**Pull request merged**
