### PR TITLE
Bayesian Suggestion Algorithm Fixes

### PR DESCRIPTION
**Pull request by mayankjuneja**
I got some errors after enabling Bayesian suggestion service on our cluster. The PR fixes the following issues:
- Update python protobufs and grpc code -- Added a command in `pkg/api/build.sh`), also added in deploy.sh
- Update PYTHONPATH to include a missing dir
- Added a missing package (`googleapis-common-protos`) in docker image

cc @YujiOshima, @jlewi, @vinaykakade 

This change is [Reviewable](https://reviewable.io/reviews/kubeflow/katib/188)

### CODE REVIEW

**Comment by YujiOshima** [comment]
@mayankjuneja Fantastic! Thanks!
I'll take a look!
/ok-to-test

**Comment by YujiOshima** [comment]
@mayankjuneja Please uncomment out [here]( https://github.com/kubeflow/katib/blob/master/test/scripts/run-tests.sh#L59) in test script .

**Comment by mayankjuneja** [comment]
@YujiOshima I am seeing following errors on presubmit job. Any ideas? Is it some cluster issue. I noticed that this is happening on another PR (https://github.com/kubeflow/katib/pull/190) as well. 

```Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4201ccfc0 0xc421e763f0  katib manifests/0-namespace.yaml 0xc421933b60 0xc421933b60  false}
from server for: "manifests/0-namespace.yaml": namespaces "katib" is forbidden: User "system:anonymous" cannot get namespaces in the namespace "katib": Unknown us
er "system:anonymous"```

**Comment by YujiOshima** [comment]
@mayankjuneja I have no idea. 
@jlewi @gaocegege @lluunn Any ideas?

**Comment by jlewi** [comment]
I'm not familiar with the RBAC model used my Katib.

It looks like one of the following might be happening

* A process isn't getting a service account
* RBAC role or role binding isn't set correctly.

The tests are using a bunch of custom scripts and manifests to run
https://github.com/kubeflow/katib/blob/master/test/scripts/run-tests.sh

I might suggest trying to deploy with kfctl.sh and trying to reproduce and debug the issue.

**Comment by YujiOshima** [comment]
@mayankjuneja I fixed CI https://github.com/kubeflow/katib/pull/194 . Please rebase master.

**Comment by mayankjuneja** [comment]
@YujiOshima Thanks! I will try it out today.

**Pull request merged**
