### PR TITLE
Drop Kubernetes v1.23 and support Kubernetes v1.26

### PR DESCRIPTION
**Pull request by tenzen-y**
**What this PR does / why we need it**:
I upgraded the Kubernetes dependencies to v1.26. By this PR, we drop support for the Kubernetes v1.23.

**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)_:
Part-of #2155

**Checklist:**

- [ ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing

/assign @andreyvelich @johnugeorge

### CODE REVIEW

**Comment by tenzen-y** [comment]
It seems that manusa/actions-setup-minikub doesn't support v1.26.

https://github.com/kubeflow/katib/actions/runs/5614686888/job/15213331797?pr=2177

So, we need to switch a way to set up minikube to https://github.com/medyagh/setup-minikube.

**Comment by tenzen-y** [comment]
@andreyvelich I rebased this PR.

**Review by andreyvelich — APPROVED** [review]
Thanks @tenzen-y!
/lgtm
/approve

**Comment by tenzen-y** [comment]
@andreyvelich Could you restart https://github.com/kubeflow/katib/actions/runs/5717370025/job/15490963428?pr=2177?

**Comment by tenzen-y** [comment]
@andreyvelich Thanks for restarting the job.
Could you restart https://github.com/kubeflow/katib/actions/runs/5717370025/job/15490963428?pr=2177 as well?

**Pull request merged**
