### PR TITLE
Add katib-cli download command for Mac

### PR DESCRIPTION
**Pull request by vinaykakade**
Added the missing command to download katib-cli on mac.

### CODE REVIEW

**Comment by gaocegege** [comment]
Hi, is there any problem? I think the changes LGTM.

**Comment by vinaykakade** [comment]
Closed this earlier to verify the CLA requirement. Signed the CLA.

I think this is now good to be merged.

**Comment by YujiOshima** [comment]
/lgtm
@vinaykakade Thanks!

**Pull request merged**
